import type { PageContentMap } from "@/lib/page-content-types";

export const SOLUTION_PAGE_CONTENT_DEFAULTS: PageContentMap = {
  "contact": {
    "contact.email": "febrianydeltrida@gmail.com",
    "contact.phone": "+62 821-5003-1305",
    "contact.address-jakarta": "Permata Hijau, Bellezza BSA, Jl. Permata Hijau No.106 lt. 1, Grogol Utara, Kebayoran Lama, Jakarta Selatan 12210",
    "contact.address-yogyakarta": "Jl. Magelang No.188, Karangwaru, Tegalrejo, Kota Yogyakarta, DIY 55242",
    "services_options.01": "BPO & Dedicated Team",
    "services_options.02": "Custom Software Development",
    "services_options.03": "Cloud & Infrastructure",
    "services_options.04": "IT Consulting",
    "feedback-seterrormessage.text-001": "Format email tidak valid. Harap masukkan email yang benar (contoh: name@domain.com).",
    "feedback-seterrormessage.text-002": "Nomor telepon tidak valid. Harap masukkan setidaknya 10 digit angka.",
    "feedback-seterrormessage.text-003": "Harap setujui persetujuan pemrosesan data terlebih dahulu.",
    "feedback-seterrormessage.text-005": "Terjadi masalah saat mengirim pesan.",
    "feedback-api-error": "Gagal menyimpan pesan ke database.",
    "faqs.0.q": "How fast is the response?",
    "faqs.0.a": "Our team typically responds within 1-2 business hours during working days.",
    "faqs.1.q": "Can I have a demo?",
    "faqs.1.a": "Yes, absolutely! Select your service of interest and our sales team will schedule a live demo session.",
    "faqs.2.q": "Is my data secure?",
    "faqs.2.a": "We adhere to strict data protection regulations (GDPR/ISO certified) and keep your information fully confidential.",
    "hero.span.text-001": "Let's Build Together",
    "hero.span.text-002": "Let's discuss",
    "hero.span.text-003": "your vision.",
    "hero.p.text-001": "Fill out the form below and our dedicated tech specialists will reach out to schedule your personalized consultation within",
    "hero.span.text-004": "1-2 business hours",
    "hero.p.text-002": ".",
    "features.span.text-005": "Fast Turnaround",
    "features.span.text-006": "NDA Protected",
    "features.span.text-007": "24/7 Support",
    "features.span.text-008": "Avg. Response Time",
    "features.span.text-009": "< 15 Mins",
    "features.img.alt-001": "Team Specialist",
    "features.p.text-003": "Tech Specialists",
    "features.p.text-004": "Ready to assist you live",
    "features.span.text-010": "Online",
    "contact.span.text-011": "Project Inquiry",
    "contact.h3.text-001": "Send Us a Message",
    "contact.p.text-005": "Tell us about your project or inquiry and we'll prepare a customized proposal.",
    "contact.p.text-006": "Message Delivered Successfully!",
    "contact.p.text-007": "Thank you for reaching out. Our team will contact you shortly.",
    "contact.p.text-008": "Unable to Send Message",
    "contact.span.text-012": "Name",
    "contact.span.text-013": "*",
    "contact.input.placeholder-001": "John Doe",
    "contact.span.text-014": "Work Email",
    "contact.span.text-015": "*",
    "contact.input.placeholder-002": "john@company.com",
    "contact.span.text-016": "Phone / WhatsApp",
    "contact.input.placeholder-003": "+62 812 3456 7890",
    "contact.span.text-017": "Company",
    "contact.input.placeholder-004": "Company Inc.",
    "features.span.text-018": "Interested In",
    "features.span.text-019": "Implementation Timeline",
    "features.option.text-001": "Select Timeline",
    "features.option.text-002": "Immediately (< 1 month)",
    "features.option.text-003": "1 - 3 months",
    "features.option.text-004": "3 - 6 months",
    "features.option.text-005": "Just exploring",
    "features.span.text-020": "Budget Estimate",
    "features.option.text-006": "Select Budget Estimate",
    "features.option.text-007": "< $5,000",
    "features.option.text-008": "$5,000 - $15,000",
    "features.option.text-009": "$15,000 - $50,000",
    "features.option.text-010": "$50,000+",
    "features.label.text-001": "Tell Us Your Needs",
    "features.span.text-021": "*",
    "features.textarea.placeholder-001": "Briefly describe your project scope, timeline, or current challenges...",
    "features.label.text-002": "I agree to be contacted and my data processed according to the",
    "features.link.href-001": "/privacy",
    "features.link.text-001": "Privacy Policy",
    "features.label.text-003": ".",
    "features.span.text-022": "Sending Message...",
    "features.span.text-023": "Send Message",
    "contact.span.text-024": "Contact Details",
    "contact.p.text-009": "Email Us",
    "contact.p.text-010": "WhatsApp / Call",
    "contact.p.text-011": "Head Office",
    "contact.p.text-012": "Working Hours",
    "contact.p.text-013": "Mon–Fri, 9:00–18:00 WIB",
    "contact.p.text-014": "Sat, 9:00–14:00 WIB",
    "contact.iframe.title-001": "Jakarta Location",
    "faq.span.text-025": "Frequently Asked Questions",
    "faq.h2.text-001": "Frequently Asked",
    "faq.span.text-026": "Questions",
    "faq.span.text-027": "0",
    "cta.span.text-028": "Instant Response Available",
    "cta.span.text-029": "More convenient via",
    "cta.span.text-030": "WhatsApp?",
    "cta.p.text-015": "Start your digital transformation journey today. Chat with our solutions architect directly for a quick consultation.",
    "cta.span.text-031": "Free Consultation Now",
    "cta.span.text-032": "24/7 WhatsApp Specialist",
    "cta.img.alt-002": "WhatsApp Consultation Specialist",
    "cta.div.text-001": "WA",
    "cta.p.text-016": "Direct Consultation",
    "cta.p.text-017": "Fast response guaranteed",
    "cta.span.text-033": "Active",
},
  "solutions-cloud": {
    "logpool.01": "[METRIC] Vertex AI inference response: 12ms",
    "logpool.02": "[SECURITY] Cloud Armor WAF blocked 0 threats",
    "logpool.03": "[FINOPS] Cost optimization engine running...",
    "logpool.04": "[SYNC] AlloyDB replication lag: <1ms",
    "logpool.05": "[BUILD] Cloud Build pipeline #8492 finished",
    "hero.span.text-001": "Next-Gen Enterprise Infrastructure",
    "hero.h1.text-001": "Google Cloud",
    "hero.span.text-002": "Modern Apps & Data",
    "hero.p.text-001": "Akselerasi transformasi digital dengan fondasi cloud Google berkecepatan tinggi. Siap untuk microservices, analytics, dan GenAI.",
    "hero.link.href-001": "/contact",
    "hero.span.text-003": "Konsultasi Gratis",
    "hero.link.href-002": "#services",
    "hero.link.text-001": "Jelajahi Kapabilitas",
    "hero.span.text-004": "99.99% SLA",
    "hero.span.text-005": "ISO 27001 & SOC 2",
    "hero.span.text-006": "Low Latency",
    "hero.span.text-007": "gcp-live-feed",
    "hero.span.text-008": "LIVE",
    "hero.span.text-009": "0.2ms",
    "hero.div.text-001": "Google GKE",
    "hero.p.text-002": "Autoscaling Active",
    "hero.span.text-010": "Petabyte",
    "hero.div.text-002": "BigQuery",
    "hero.p.text-003": "Data Lakehouse",
    "hero.span.text-011": "LIVE STREAM LOGS",
    "features.span.text-012": "Ecosystem Stack",
    "features.h2.text-001": "Google Cloud Core Services",
    "features.p.text-004": "Layanan komprehensif komputasi, storage, keamanan & DevOps.",
    "architecture.span.text-013": "Interactive Blueprints",
    "architecture.h2.text-002": "Ready-to-Use Architecture",
    "architecture.button.text-001": "Analytics",
    "architecture.button.text-002": "Microservices",
    "architecture.button.text-003": "GenAI Agent",
    "architecture.div.text-003": "Modern Analytics Warehouse",
    "architecture.h3.text-001": "Real-Time Enterprise Analytics Engine",
    "architecture.p.text-005": "Sentralisasi & analisis jutaan data real-time dengan BigQuery, Pub/Sub, Dataflow & Looker BI.",
    "architecture.span.text-014": "01. Ingestion",
    "architecture.div.text-004": "Pub/Sub & Dataflow Real-time Stream",
    "architecture.span.text-015": "02. Storage & SQL",
    "architecture.div.text-005": "BigQuery Petabyte Analytics",
    "architecture.span.text-016": "03. BI & Dashboards",
    "architecture.div.text-006": "Looker Enterprise Business Intelligence",
    "architecture.div.text-007": "Microservices Mesh",
    "architecture.h3.text-002": "GKE Enterprise Container Platform",
    "architecture.p.text-006": "Arsitektur kontainer berskala tinggi dengan visibilitas Service Mesh & zero-trust network.",
    "architecture.span.text-017": "01. CI/CD Pipeline",
    "architecture.div.text-008": "Cloud Build & GitHub Actions Sync",
    "architecture.span.text-018": "02. Mesh & Security",
    "architecture.div.text-009": "Anthos Service Mesh & mTLS Encryption",
    "architecture.span.text-019": "03. Deployment",
    "architecture.div.text-010": "Zero-Downtime Canary Rollout",
    "architecture.div.text-011": "GenAI Solutions",
    "architecture.h3.text-003": "Enterprise RAG & AI Agent on Vertex AI",
    "architecture.p.text-007": "Pengembangan AI Agent & sistem pencarian cerdas berbasis data internal secara privat dan aman.",
    "architecture.span.text-020": "01. Vector Database",
    "architecture.div.text-012": "Vertex Vector Search & Embeddings",
    "architecture.span.text-021": "02. Guardrails",
    "architecture.div.text-013": "Custom AI Prompt & Safety Filters",
    "architecture.span.text-022": "03. Data Privacy",
    "architecture.div.text-014": "Enterprise Private Data Shield",
    "architecture.span.text-023": "Seamless Transition",
    "architecture.h2.text-003": "Migrasi Tanpa Downtime & Risk",
    "architecture.span.text-024": "Migration Pipeline",
    "architecture.span.text-025": "Active Sync",
    "architecture.span.text-026": "Source Workload Mapped",
    "architecture.span.text-027": "100%",
    "architecture.span.text-028": "Data Syncing",
    "architecture.span.text-029": "88%",
    "architecture.span.text-030": "Didukung Google Cloud Certified Architect profesional.",
    "cta.h2.text-004": "Siap Mentransformasi Cloud Anda?",
    "cta.p.text-008": "Konsultasikan arsitektur, migrasi, atau optimasi biaya Google Cloud hari ini.",
    "cta.link.href-003": "/contact",
    "cta.link.text-002": "Konsultasi Gratis",
      "live-logs.initial.01": "[INIT] Connecting to Google Cloud Region asia-southeast2...",
    "live-logs.initial.02": "[INFO] GKE Cluster Autoscaler status: OPTIMAL",
    "live-logs.initial.03": "[INFO] BigQuery streaming buffer active (0.2ms latency)",
    "cards.dataset-01.01.title": "Scalable by Design",
    "cards.dataset-01.01.desc": "Skala global otomatis dengan load balancing cerdas & standar SRE.",
    "cards.dataset-01.02.title": "Data & AI Ready",
    "cards.dataset-01.02.desc": "BigQuery & Vertex AI terintegrasi untuk kecerdasan bisnis mutakhir.",
    "cards.dataset-01.03.title": "Zero-Trust Posture",
    "cards.dataset-01.03.desc": "Proteksi IAM, VPC Service Controls & Cloud Armor.",
    "cards.dataset-01.04.title": "Cost Efficient",
    "cards.dataset-01.04.desc": "Optimasi TCO dengan Committed Use Discounts dan FinOps.",
    "cards.dataset-02.01.title": "Compute Engine",
    "cards.dataset-02.01.items.01": "Google Kubernetes Engine (GKE)",
    "cards.dataset-02.01.items.02": "Cloud Run (Serverless)",
    "cards.dataset-02.01.items.03": "Compute Engine (Custom VMs)",
    "cards.dataset-02.01.items.04": "App Engine Platform",
    "cards.dataset-02.02.title": "Storage & Databases",
    "cards.dataset-02.02.items.01": "Cloud Storage (High-Speed)",
    "cards.dataset-02.02.items.02": "AlloyDB & Cloud SQL",
    "cards.dataset-02.02.items.03": "Filestore (NFS Enterprise)",
    "cards.dataset-02.02.items.04": "Persistent Disk & DR",
    "cards.dataset-02.03.title": "Data Analytics & AI",
    "cards.dataset-02.03.items.01": "BigQuery Enterprise",
    "cards.dataset-02.03.items.02": "Vertex AI & GenAI Studio",
    "cards.dataset-02.03.items.03": "Dataflow Real-Time Streaming",
    "cards.dataset-02.03.items.04": "Looker Business Intelligence",
    "cards.dataset-02.04.title": "Global Networking",
    "cards.dataset-02.04.items.01": "Enterprise VPC & Cloud NAT",
    "cards.dataset-02.04.items.02": "Cloud Load Balancing",
    "cards.dataset-02.04.items.03": "Cloud CDN Global Edge",
    "cards.dataset-02.04.items.04": "Cloud Armor WAF Protection",
    "cards.dataset-02.05.title": "Security & IAM",
    "cards.dataset-02.05.items.01": "Context-Aware Access & IAM",
    "cards.dataset-02.05.items.02": "Key Management (KMS)",
    "cards.dataset-02.05.items.03": "Security Command Center",
    "cards.dataset-02.05.items.04": "Chronicle SIEM & SOAR",
    "cards.dataset-02.06.title": "DevOps & SRE",
    "cards.dataset-02.06.items.01": "Cloud Build & Artifact Registry",
    "cards.dataset-02.06.items.02": "Google Cloud Deploy",
    "cards.dataset-02.06.items.03": "Cloud Operations Suite",
    "cards.dataset-02.06.items.04": "Automated SRE Incident",
    "cards.dataset-03.01.title": "Discovery & TCO",
    "cards.dataset-03.01.desc": "Pemetaan legacy & estimasi hemat.",
    "cards.dataset-03.02.title": "Landing Zone",
    "cards.dataset-03.02.desc": "Setup IAM & struktur VPC awal.",
    "cards.dataset-03.03.title": "Pilot Workload",
    "cards.dataset-03.03.desc": "Pengujian migrasi tanpa mengganggu.",
    "cards.dataset-03.04.title": "FinOps Optimization",
    "cards.dataset-03.04.desc": "Monitoring & efisiensi berkala.",
},
  "solutions-iso": {
    "pool.01": "[ITSMS] ISO 20000 Incident Management OLA verified",
    "pool.02": "[BCMS] ISO 22301 Disaster Recovery Simulation Passed",
    "pool.03": "[PRIVACY] ISO 27701 Data Processor Agreement Auto-Audited",
    "pool.04": "[AUDIT] External Stage 2 Audit Readiness: 99.4%",
    "pool.05": "[SECURITY] Zero Major Non-Conformity Detected",
    "pool.06": "[EVIDENCE] Continuous Vulnerability Assessment Logged",
    "standardsdata.27001.code": "ISO/IEC 27001:2022",
    "standardsdata.27001.name": "Information Security Management System (ISMS)",
    "standardsdata.27001.controls": "93 Control Clauses",
    "standardsdata.27001.focus": "Kerahasiaan, Integritas, & Ketersediaan Data Aset Informasi",
    "standardsdata.27001.badge": "SMKI / ISMS",
    "standardsdata.27001.highlights.01": "Annex A Security Controls",
    "standardsdata.27001.highlights.02": "Risk Assessment Framework",
    "standardsdata.27001.highlights.03": "SoA (Statement of Applicability)",
    "standardsdata.27001.highlights.04": "MFA & Access Management",
    "standardsdata.20000.code": "ISO/IEC 20000-1:2018",
    "standardsdata.20000.name": "IT Service Management System (ITSMS)",
    "standardsdata.20000.controls": "Service Lifecycle Clauses",
    "standardsdata.20000.focus": "Kualitas, SLA, & Efisiensi Layanan Teknologi Informasi",
    "standardsdata.20000.badge": "ITSMS",
    "standardsdata.20000.highlights.01": "SLA & OLA Monitoring",
    "standardsdata.20000.highlights.02": "Incident & Change Management",
    "standardsdata.20000.highlights.03": "Capacity Planning",
    "standardsdata.20000.highlights.04": "Service Desk Best Practice",
    "standardsdata.22301.code": "ISO 22301:2019",
    "standardsdata.22301.name": "Business Continuity Management System (BCMS)",
    "standardsdata.22301.controls": "Business Impact Analysis",
    "standardsdata.22301.focus": "Ketahanan Operasional Bisnis & Pemulihan Bencana (DRP)",
    "standardsdata.22301.badge": "BCMS",
    "standardsdata.22301.highlights.01": "Business Impact Analysis (BIA)",
    "standardsdata.22301.highlights.02": "Disaster Recovery Plan (DRP)",
    "standardsdata.22301.highlights.03": "Crisis Communication Protocol",
    "standardsdata.22301.highlights.04": "RTO & RPO Benchmarking",
    "standardsdata.27701.code": "ISO/IEC 27701:2019",
    "standardsdata.27701.name": "Privacy Information Management System (PIMS)",
    "standardsdata.27701.controls": "GDPR & UU PDP Alignment",
    "standardsdata.27701.focus": "Perlindungan Data Pribadi (PDP) & Tata Kelola Privasi",
    "standardsdata.27701.badge": "PIMS / PDP",
    "standardsdata.27701.highlights.01": "Personal Data Processing (PII)",
    "standardsdata.27701.highlights.02": "Data Protection Impact Assessment (DPIA)",
    "standardsdata.27701.highlights.03": "Data Subject Rights Management",
    "standardsdata.27701.highlights.04": "Cross-Border Data Transfer",
    "hero.span.text-001": "ISO 27001 • ISO 20000 • ISO 22301 • ISO 27701",
    "hero.h1.text-001": "Layanan Kepatuhan &",
    "hero.h1.text-002": "Compliance &",
    "hero.span.text-002": "Sertifikasi ISO",
    "hero.span.text-003": "ISO Certification",
    "hero.p.text-001": "Dampingi organisasi Anda meraih dan mempertahankan standar internasional keamanan informasi, manajemen layanan IT, dan kelangsungan bisnis dengan garansi kelulusan audit 100%.",
    "hero.p.text-002": "Guide your organization to achieve and maintain international information security, IT service management, and business continuity standards with guaranteed 100% audit pass rate.",
    "hero.link.href-001": "/contact",
    "hero.span.text-004": "Konsultasi Sekarang",
    "hero.span.text-005": "Consult Now",
    "hero.span.text-006": "100% Audit Pass Rate",
    "hero.span.text-007": "Full Documentation Support",
    "hero.span.text-008": "IRCA Lead Auditors",
    "hero.span.text-009": "ISO_COMPLIANCE_HUB_v4.0",
    "hero.span.text-010": "AUDIT READY",
    "hero.span.text-011": "ISO 27001 ISMS Readiness",
    "hero.span.text-012": "99.4% Compliant",
    "hero.span.text-013": "Annex A Controls",
    "hero.span.text-014": "93 / 93 Verified",
    "hero.span.text-015": "Major Non-Conformity",
    "hero.span.text-016": "0 Non-Conformity",
    "hero.span.text-017": "REALTIME AUDIT FEED",
    "hero.span.text-018": ">",
    "hero.span.text-019": "SIMULASI TINGKAT KERUMITAN & ESTIMASI WAKTU",
    "hero.h2.text-001": "Kalkulator Estimasi Implementasi ISO",
    "hero.p.text-003": "Geser jumlah personel/skala organisasi untuk melihat perkiraan durasi pendampingan hingga sertifikat terbit secara real-time.",
    "hero.span.text-020": "Jumlah Karyawan / Skala Organisasi:",
    "hero.span.text-021": "Karyawan",
    "hero.span.text-022": "< 20 (Startup)",
    "hero.span.text-023": "100 (SME)",
    "hero.span.text-024": "500+ (Enterprise)",
    "hero.span.text-025": "Estimasi Durasi Project",
    "hero.p.text-004": "Terhitung dari Gap Analysis hingga Stage 2 Audit Eksternal.",
    "hero.span.text-026": "Jaminan Kelulusan",
    "hero.div.text-001": "100% Pass Rate",
    "hero.p.text-005": "Garansi pendampingan ulang tanpa biaya tambahan jika ada insiden.",
    "hero.span.text-027": "KERANGKA KERJA UTAMA",
    "hero.h2.text-002": "Cakupan Standar Sertifikasi ISO",
    "hero.p.text-006": "Pilih standar ISO di bawah untuk mempelajari klausul utama, fokus kontrol, serta hasil deliverables project.",
    "hero.span.text-028": "Estimasi:",
    "hero.strong.text-001": "Fokus Utama:",
    "hero.h4.text-001": "Target Output & Certification",
    "hero.span.text-029": "Cakupan Kontrol",
    "hero.span.text-030": "Hasil Konsultasi",
    "hero.span.text-031": "Dokumentasi Lengkap + Sertifikat Resmi",
    "hero.link.href-002": "/contact",
    "hero.span.text-032": "Minta Proposal ISO",
    "hero.span.text-033": "METODOLOGI TERSTRUKTUR",
    "hero.h2.text-003": "Tahapan Konsultasi & Sertifikasi",
    "hero.p.text-007": "Pendekatan 4 langkah terukur hingga organisasi Anda meraih sertifikasi resmi.",
    "hero.span.text-034": "STEP 0",
    "hero.span.text-035": "Main Deliverable",
    "hero.span.text-036": "NILAI TAMBAH",
    "hero.h2.text-004": "Mengapa Memilih Layanan Kami?",
    "hero.span.text-037": "AKREDITASI GLOBAL",
    "hero.h2.text-005": "Mitra Badan Sertifikasi",
    "hero.p.text-008": "Kami memfasilitasi pendampingan audit dengan Badan Sertifikasi Internasional terkemuka yang terakreditasi KAN, UKAS, JAS-ANZ, dan ANAB untuk pengakuan global.",
    "hero.span.text-038": "KAN (Komite Akreditasi Nasional)",
    "hero.span.text-039": "✓ Terakreditasi",
    "hero.span.text-040": "UKAS (United Kingdom Accreditation)",
    "hero.span.text-041": "✓ Terakreditasi",
    "hero.span.text-042": "ANAB & JAS-ANZ Accredited",
    "hero.span.text-043": "✓ Terakreditasi",
    "cta.h2.text-006": "Siap Meraih Sertifikasi ISO Organisasi Anda?",
    "cta.p.text-009": "Jadwalkan sesi konsultasi gratis dan Gap Analysis awal bersama tim IRCA Lead Auditor kami hari ini.",
    "cta.link.href-003": "/contact",
    "cta.span.text-044": "Jadwalkan Konsultasi Gratis",
      "live-logs.initial.01": "[ISMS] ISO 27001 Annex A.5 Security Policies verified",
    "live-logs.initial.02": "[COMPLIANCE] Risk Register updated (0 High Risks)",
    "live-logs.initial.03": "[EVIDENCE] Access Control Logs & MFA Enforcement synced",
    "standardsdata.27001.timeframe.id": "4 - 6 Bulan",
    "standardsdata.27001.timeframe.en.id": "3 - 4 Bulan",
    "standardsdata.27001.timeframe.en.en": "2 - 3 Bulan",
    "standardsdata.20000.timeframe.id": "3 - 5 Bulan",
    "standardsdata.20000.timeframe.en.id": "2 - 4 Bulan",
    "standardsdata.20000.timeframe.en.en": "2 - 3 Bulan",
    "standardsdata.22301.timeframe.id": "4 - 5 Bulan",
    "standardsdata.22301.timeframe.en.id": "3 - 4 Bulan",
    "standardsdata.22301.timeframe.en.en": "2 - 3 Bulan",
    "standardsdata.27701.timeframe.id": "3 - 4 Bulan",
    "standardsdata.27701.timeframe.en.id": "2 - 3 Bulan",
    "standardsdata.27701.timeframe.en.en": "1 - 2 Bulan",
    "cards.dataset-01.27001.label": "ISO 27001",
    "cards.dataset-01.20000.label": "ISO 20000",
    "cards.dataset-01.22301.label": "ISO 22301",
    "cards.dataset-01.27701.label": "ISO 27701",
    "cards.dataset-02.01.title": "Gap Analysis",
    "cards.dataset-02.01.desc": "Evaluasi komprehensif kondisi sistem, kebijakan, & infrastruktur eksisting terhadap klausa ISO.",
    "cards.dataset-02.02.title": "Dokumentasi",
    "cards.dataset-02.02.desc": "Penyusunan kebijakan, SOP, pedoman kerja, Risk Assessment, & Statement of Applicability (SoA).",
    "cards.dataset-02.03.title": "Implementasi & Audit Internal",
    "cards.dataset-02.03.desc": "Penerapan kontrol teknis, awareness training karyawan, & eksekusi audit internal awal.",
    "cards.dataset-02.04.title": "Audit Sertifikasi Eksternal",
    "cards.dataset-02.04.desc": "Pendampingan penuh tim konsultan saat Audit Stage 1 & Stage 2 oleh Badan Sertifikasi Resmi.",
    "cards.dataset-03.01.title": "Jaminan Kelulusan 100%",
    "cards.dataset-03.01.desc": "Pendampingan berlanjut tanpa biaya tambahan hingga sertifikat diterbitkan resmi.",
    "cards.dataset-03.02.title": "Tim IRCA Lead Auditor",
    "cards.dataset-03.02.desc": "Konsultan bersertifikasi internasional dengan pengalaman audit di berbagai industri enterprise.",
    "cards.dataset-03.03.title": "Dokumentasi Praktis & Efisien",
    "cards.dataset-03.03.desc": "Penyusunan SOP disesuaikan dengan alur bisnis eksisting tanpa membebani operasional.",
    "cards.dataset-03.04.title": "Dukungan Tools & Templates",
    "cards.dataset-03.04.desc": "Akses ke pustaka template kebijakan ISO & alat pengumpul bukti audit digital.",
},
  "solutions-it": {
    "pool.01": "[SECURITY] Zero-Trust session refreshed for 120 users",
    "pool.02": "[AUTOMATION] Onboarding workflow triggered for New Hire #382",
    "pool.03": "[MONITORING] CPU Spike on DB-Cluster-02 resolved automatically",
    "pool.04": "[CSAT] Ticket #9810 closed with 5/5 Rating",
    "hero.span.text-001": "NEXT-GEN IT MANAGEMENT • SERVICE DESK • ENDPOINT SECURITY",
    "hero.span.text-002": "NEXT-GEN IT MANAGEMENT • SERVICE DESK • ENDPOINT SECURITY",
    "hero.h1.text-001": "Kelola Infrastruktur IT",
    "hero.h1.text-002": "Manage IT Infrastructure",
    "hero.span.text-003": "Tanpa Hambatan",
    "hero.span.text-004": "Without Friction",
    "hero.p.text-001": "Otomatisasi IT Service Desk, pemantauan aset komprehensif, patching otomatis, serta perlindungan endpoint tingkat lanjut—semua terpusat dengan jaminan SLA transparan.",
    "hero.p.text-002": "Automate IT Service Desk, real-time asset tracking, automated patching, and enterprise endpoint security under clear SLAs.",
    "hero.link.href-001": "/contact",
    "hero.span.text-005": "Diskusikan Kebutuhan",
    "hero.span.text-006": "Discuss Needs",
    "hero.div.text-001": "System Availability",
    "hero.div.text-002": "Avg Resolution (MTTR)",
    "hero.div.text-003": "24/7/365",
    "hero.div.text-004": "NOC Operations",
    "hero.span.text-007": "NOC_CONTROL_v4.2",
    "hero.span.text-008": "ONLINE",
    "hero.button.text-001": "Service Desk",
    "hero.button.text-002": "Asset Tracking",
    "hero.button.text-003": "Endpoint SOC",
    "hero.span.text-009": "Service Desk L1-L3",
    "hero.span.text-010": "SLA: 99.8%",
    "hero.p.text-003": "Routing insiden cerdas, otomatisasi penugasan tiket, dan templat penyelesaian cepat.",
    "hero.span.text-011": "MTTR: 12 min",
    "hero.span.text-012": "CSAT: 4.9/5",
    "hero.span.text-013": "CMDB & Asset Inventory",
    "hero.span.text-014": "3,420 Active Assets",
    "hero.p.text-004": "Penemuan perangkat otomatis, audit lisensi, dan pelacakan lifecycle hardware.",
    "hero.span.text-015": "License: Compliant",
    "hero.span.text-016": "Auto-Discovery ON",
    "hero.span.text-017": "Managed EDR & Patching",
    "hero.span.text-018": "Zero Vulnerabilities",
    "hero.p.text-005": "Penerapan patch sistem otomatis, antivirus generasi baru, dan isolasi ancaman instant.",
    "hero.span.text-019": "Agent: Active",
    "hero.span.text-020": "Patch Level: Latest",
    "hero.span.text-021": "LIVE NOC CONSOLE FEED",
    "hero.span.text-022": ">",
    "hero.span.text-023": "MODUL TERPADU",
    "hero.span.text-024": "UNIFIED MODULES",
    "hero.h2.text-001": "Paket Modul Layanan IT",
    "hero.h2.text-002": "Core IT Service Modules",
    "hero.button.text-004": "ITSM Service Desk",
    "hero.button.text-005": "Asset CMDB",
    "hero.button.text-006": "Endpoint Security",
    "hero.h3.text-001": "ITSM / Service Desk",
    "hero.span.text-025": "Manajemen Insiden, Permintaan, Perubahan, & Masalah",
    "hero.span.text-026": "Incident, Request, Change, & Problem Management",
    "hero.span.text-027": "Portal Mandiri (Self-Service) & Knowledge Base",
    "hero.span.text-028": "Knowledge Base & Self-Service Portal",
    "hero.span.text-029": "Aturan SLA/OLA, persetujuan & eskalasi bertingkat",
    "hero.span.text-030": "SLA/OLA rules, multi-tier approvals",
    "hero.h3.text-002": "Aset & Inventaris IT",
    "hero.h3.text-003": "IT Asset & Inventory",
    "hero.span.text-031": "Penemuan otomatis (CMDB) & pengukuran software",
    "hero.span.text-032": "Auto-discovery, CMDB, & software metering",
    "hero.span.text-033": "Kepatuhan lisensi & manajemen kontrak vendor",
    "hero.span.text-034": "License compliance & vendor contract mgmt",
    "hero.span.text-035": "Siklus hidup aset penuh (Procure-to-Retire)",
    "hero.span.text-036": "Full asset lifecycle (Procure-to-Retire)",
    "hero.h3.text-004": "Keamanan Endpoint",
    "hero.h3.text-005": "Endpoint Security",
    "hero.span.text-037": "MDM/MAM Windows, macOS, Linux, iOS, & Android",
    "hero.span.text-038": "Patching terjadwal, kebijakan remote & akses",
    "hero.span.text-039": "Automated patching, remote policy, & access control",
    "hero.span.text-040": "Antivirus/EDR terintegrasi & enkripsi disk",
    "hero.span.text-041": "Integrated EDR/AV & full disk encryption",
    "hero.span.text-042": "EFISIENSI MAKSIMAL",
    "hero.span.text-043": "MAXIMUM EFFICIENCY",
    "hero.h2.text-003": "Otomatisasi Operasi IT",
    "hero.h2.text-004": "IT Operations Automation",
    "hero.p.text-006": "Eliminasi pekerjaan manual berulang menggunakan alur kerja otomatis berbasis kejadian (event-driven workflow).",
    "hero.p.text-007": "Eliminate repetitive tasks with event-driven automated workflows and scheduled tasks.",
    "hero.span.text-044": "DUKUNGAN EKOSISTEM",
    "hero.span.text-045": "ECOSYSTEM COMPATIBILITY",
    "hero.h2.text-005": "Integrasi Sistem",
    "hero.h2.text-006": "System Integrations",
    "hero.h4.text-001": "Identitas & Direktori",
    "hero.h4.text-002": "Identity & Directory",
    "hero.p.text-008": "Active Directory, Azure AD / Entra ID, Okta, Google Workspace SSO.",
    "hero.h4.text-003": "ChatOps & Kolaborasi",
    "hero.h4.text-004": "ChatOps & Collaboration",
    "hero.p.text-009": "Microsoft Teams, Slack, Email Gateways, Telephony, Jira Cloud API.",
    "hero.h4.text-005": "Observabilitas & Keamanan",
    "hero.h4.text-006": "Observability & Security",
    "hero.p.text-010": "SIEM / SOAR tools, NMS exporters, Endpoint Logs ke Central Data Lake.",
    "hero.span.text-046": "SKEMA KERJASAMA",
    "hero.span.text-047": "ENGAGEMENT MODELS",
    "hero.h2.text-007": "Pilihan Paket Layanan",
    "hero.h2.text-008": "Service Package Options",
    "hero.p.text-011": "Fleksibel sesuai dengan skala dan kompleksitas operasional IT perusahaan Anda.",
    "hero.p.text-012": "Flexible plans tailored to your organization scale and requirements.",
    "hero.span.text-048": "SETUP PACK",
    "hero.h3.text-006": "Implementation Pack",
    "hero.p.text-013": "Pengaturan awal cepat + transfer pengetahuan tim.",
    "hero.p.text-014": "Quick rollout + full knowledge transfer to internal IT.",
    "hero.li.text-001": "Asesmen alur kerja & proses IT",
    "hero.li.text-002": "Process assessment & workflow design",
    "hero.li.text-003": "Konfigurasi modul & integrasi dasar",
    "hero.li.text-004": "Module setup & basic SSO integration",
    "hero.li.text-005": "Pelatihan admin & penyerahan SOP",
    "hero.li.text-006": "Admin training & full SOP handover",
    "hero.link.href-002": "/contact",
    "hero.link.text-001": "Minta Penawaran",
    "hero.link.text-002": "Request a Quote",
    "features.div.text-005": "RECOMMENDED",
    "features.span.text-049": "FULL MANAGED",
    "features.h3.text-007": "Managed Service",
    "features.p.text-015": "Dukungan penuh operasional harian IT oleh pakar kami.",
    "features.p.text-016": "End-to-end daily IT service operations handled by our team.",
    "features.li.text-007": "Dukungan Service Desk L1–L3 sesuai SLA",
    "features.li.text-008": "Service desk L1–L3 with SLA compliance",
    "features.li.text-009": "Patching, monitoring, & penanganan insiden",
    "features.li.text-010": "Proactive patching & incident response",
    "features.li.text-011": "Laporan bulanan & evaluasi berkala",
    "features.li.text-012": "Monthly KPI reports & continuous review",
    "features.link.href-003": "/contact",
    "features.link.text-003": "Minta Penawaran",
    "features.link.text-004": "Request a Quote",
    "features.span.text-050": "ENTERPRISE SOC",
    "features.h3.text-008": "Managed Service Plus",
    "features.p.text-017": "Operasional IT lengkap ditambah keamanan & kepatuhan.",
    "features.p.text-018": "Full IT operations plus advanced security & compliance.",
    "features.li.text-013": "Managed EDR/AV & vulnerability scanning",
    "features.li.text-014": "Managed EDR/AV & vulnerability scan",
    "features.li.text-015": "Security hardening & Zero-Trust access",
    "features.li.text-016": "Security hardening & Zero-Trust controls",
    "features.li.text-017": "Latihan simulasi ancaman berkala",
    "features.li.text-018": "Periodic risk reviews & tabletop exercises",
    "features.link.href-004": "/contact",
    "features.link.text-005": "Minta Penawaran",
    "features.link.text-006": "Request a Quote",
    "cta.h2.text-009": "Tingkatkan Efisiensi IT Anda Sekarang",
    "cta.h2.text-010": "Elevate Your IT Operations Today",
    "cta.p.text-019": "Diskusikan kebutuhan manajemen IT perusahaan Anda dengan tim spesialis kami untuk mendapatkan rekomendasi terbaik.",
    "cta.p.text-020": "Consult your service desk and endpoint security strategy with our enterprise IT specialists.",
    "cta.link.href-005": "/contact",
    "cta.span.text-051": "Konsultasi Gratis",
    "cta.span.text-052": "Free Consultation",
      "metrics.uptime": "99.98%",
    "metrics.mttr": "11.4 min",
    "live-logs.initial.01": "[ITS-01] Auto-routing ticket #9842 to Tier-2 Support",
    "live-logs.initial.02": "[ASSET] Mac Studio M3 Max synced with Endpoint Manager",
    "live-logs.initial.03": "[PATCH] Security Hotfix KB503819 deployed to 340 devices",
    "cards.dataset-01.01.title.id": "Respon Tiket Cepat",
    "cards.dataset-01.01.title.en": "Faster Ticket Resolution",
    "cards.dataset-01.01.desc.id": "Routing otomatis, templat solusi cerdas, & SLA ketat.",
    "cards.dataset-01.01.desc.en": "Smart routing, response templates, and clear SLAs.",
    "cards.dataset-01.02.title.id": "Visibilitas Aset Real-Time",
    "cards.dataset-01.02.title.en": "Real-Time Asset Visibility",
    "cards.dataset-01.02.desc.id": "Inventaris penuh untuk hardware, lisensi, & software.",
    "cards.dataset-01.02.desc.en": "Real-time inventory for devices, licenses, & software.",
    "cards.dataset-01.03.title.id": "Keamanan Berlapis",
    "cards.dataset-01.03.title.en": "Secure by Default",
    "cards.dataset-01.03.desc.id": "Automated patching, hardening, & integrasi EDR/AV.",
    "cards.dataset-01.03.desc.en": "Patch mgmt, hardening, integrated EDR/AV.",
    "cards.dataset-01.04.title.id": "Analitik Operasional",
    "cards.dataset-01.04.title.en": "Operational Insights",
    "cards.dataset-01.04.desc.id": "Dasbor KPI, tren insiden, & laporan audit otomatis.",
    "cards.dataset-01.04.desc.en": "KPI dashboard, incident trends, and audit trail.",
    "cards.dataset-02.01.title.id": "Auto-Routing Tiket",
    "cards.dataset-02.01.title.en": "Auto-Ticket Routing",
    "cards.dataset-02.01.desc.id": "Berdasarkan beban tim & kategori insiden",
    "cards.dataset-02.01.desc.en": "Based on team load & incident category",
    "cards.dataset-02.02.title.id": "User Onboarding",
    "cards.dataset-02.02.title.en": "User Onboarding",
    "cards.dataset-02.02.desc.id": "Otomatisasi provisi akun & akses perangkat",
    "cards.dataset-02.02.desc.en": "Automated user provisioning & device setup",
    "cards.dataset-02.03.title.id": "Patching Terjadwal",
    "cards.dataset-02.03.title.en": "Scheduled Patching",
    "cards.dataset-02.03.desc.id": "Pembaruan OS & software tanpa downtime",
    "cards.dataset-02.03.desc.en": "Seamless OS & app updates without friction",
    "cards.dataset-02.04.title.id": "Alerting Webhook",
    "cards.dataset-02.04.title.en": "Webhook Alerts",
    "cards.dataset-02.04.desc.id": "Integrasi langsung dari sistem NMS/Monitoring",
    "cards.dataset-02.04.desc.en": "Direct triggers from NMS/Monitoring tools",
},
  "solutions-sobot": {
    "channelmessages.wa.channelname": "WhatsApp Business API",
    "channelmessages.wa.usermsg": "Halo, saya mau cek status pesanan #ORD-89211 dong.",
    "channelmessages.wa.aimsg": "Pesanan #ORD-89211 sedang dikirim oleh kurir (JNT) dan diperkirakan tiba hari ini sebelum pukul 17:00 WIB. Klik link untuk lacak live location: sobot.link/track",
    "channelmessages.ig.channelname": "Instagram Direct Message",
    "channelmessages.ig.usermsg": "Min, produk promo diskon 50% masih ready?",
    "channelmessages.ig.aimsg": "Masih ready kak! Promo berakhir dalam 2 jam lagi. Mau AI kirimkan langsung katalog & voucher checkout-nya ke DM ini?",
    "channelmessages.web.channelname": "Website Live Chat Widget",
    "channelmessages.web.usermsg": "Bagaimana cara integrasi AI Sobot ke CRM Salesforce kami?",
    "channelmessages.web.aimsg": "Sangat mudah! Sobot menyediakan Native API & Webhook siap pakai. Tim teknis kami dapat menyelesaikan integrasi dalam < 24 jam.",
    "channelmessages.voice.channelname": "Voice AI Auto-Call",
    "channelmessages.voice.usermsg": "[Voice Call Active] Halo Sobot Assistant...",
    "channelmessages.voice.aimsg": "Halo Pak Budi! Saya AI Voice Sobot. Jadwal janji temu Anda dengan konsultan kami ditetapkan esok pukul 10:00 WIB. Apakah ingin dikonfirmasi?",
    "industrydata.retail.title": "Retail & E-commerce",
    "industrydata.retail.subtitle": "Tingkatkan konversi penjualan & bantu lacak pesanan otomatis.",
    "industrydata.retail.features.01.title": "Bantuan Pra-Penjualan",
    "industrydata.retail.features.01.desc": "Rekomendasi produk personal, FAQ, dan perbandingan harga.",
    "industrydata.retail.features.02.title": "Otomatisasi Pembayaran",
    "industrydata.retail.features.02.desc": "Pengingat keranjang (cart recovery) dan bantuan instruksi bayar.",
    "industrydata.retail.features.03.title": "Layanan Purna Jual",
    "industrydata.retail.features.03.desc": "Lacak resi instan, klaim garansi, dan retur tanpa ribet.",
    "industrydata.retail.illustrationtitle": "Shopping Assistant & Cart Recovery",
    "industrydata.financial.title": "Financial Services & Banking",
    "industrydata.financial.subtitle": "Layanan keuangan aman dengan kepatuhan ISO & GDPR.",
    "industrydata.financial.features.01.title": "KYC & Registrasi",
    "industrydata.financial.features.01.desc": "Onboarding nasabah, verifikasi dokumen, dan cek limit.",
    "industrydata.financial.features.02.title": "Navigasi Transaksi",
    "industrydata.financial.features.02.desc": "Info mutasi, blokir kartu darurat, dan peringatan fraud.",
    "industrydata.financial.features.03.title": "Edukasi Produk",
    "industrydata.financial.features.03.desc": "Simulasi pinjaman, asuransi, dan panduan investasi.",
    "industrydata.financial.illustrationtitle": "Secure Banking & Verification Portal",
    "industrydata.gaming.title": "Gaming & Entertainment",
    "industrydata.gaming.subtitle": "Dukungan player 24/7 untuk meningkatkan retensi pemain.",
    "industrydata.gaming.features.01.title": "Layanan Player 24/7",
    "industrydata.gaming.features.01.desc": "Penanganan keluhan top-up & bug game secara instan.",
    "industrydata.gaming.features.02.title": "Pengingat Event & Update",
    "industrydata.gaming.features.02.desc": "Notifikasi patch note, membership, dan event khusus.",
    "industrydata.gaming.features.03.title": "Pemasaran Segmentasi",
    "industrydata.gaming.features.03.desc": "Tagging perilaku player untuk promo in-game yang akurat.",
    "industrydata.gaming.illustrationtitle": "Player Support & Event Engagement",
    "industrydata.education.title": "Education & University",
    "industrydata.education.subtitle": "Solusi fleksibel untuk mahasiswa, dosen, dan calon pendaftar.",
    "industrydata.education.features.01.title": "Informasi Pendaftaran",
    "industrydata.education.features.01.desc": "Bot pendaftaran, info beasiswa, dan syarat masuk.",
    "industrydata.education.features.02.title": "Layanan Mahasiswa",
    "industrydata.education.features.02.desc": "Cek jadwal kuliah, transkrip nilai, dan administrasi.",
    "industrydata.education.features.03.title": "Broadcast Otomatis",
    "industrydata.education.features.03.desc": "Pengumuman ujian, perkuliahan, dan batas pembayaran.",
    "industrydata.education.illustrationtitle": "Campus AI Support Center",
    "industrydata.enterprise.title": "Enterprise & Corporate Services",
    "industrydata.enterprise.subtitle": "Dukungan internal perusahaan untuk IT, HR, dan Finance.",
    "industrydata.enterprise.features.01.title": "IT Helpdesk Automated",
    "industrydata.enterprise.features.01.desc": "Tiket kendala IT, permintaan akses, dan kuesioner.",
    "industrydata.enterprise.features.02.title": "HR Self-Service",
    "industrydata.enterprise.features.02.desc": "Pengajuan cuti, cek slip gaji, dan info benefit karyawan.",
    "industrydata.enterprise.features.03.title": "Finance Operations",
    "industrydata.enterprise.features.03.desc": "Verifikasi invoice, klaim reimbursement, dan approval.",
    "industrydata.enterprise.illustrationtitle": "Internal Employee Assistance Desk",
    "industrydata.life.title": "Public & Life Services",
    "industrydata.life.subtitle": "Pelayanan publik cepat tanggap untuk skala pengguna besar.",
    "industrydata.life.features.01.title": "Layanan Pengaduan",
    "industrydata.life.features.01.desc": "Penerimaan aduan warga dan penjejakan status laporan.",
    "industrydata.life.features.02.title": "Informasi Tagihan Publik",
    "industrydata.life.features.02.desc": "Cek tagihan listrik/air dan integrasi pembayaran.",
    "industrydata.life.features.03.title": "Pemberitahuan Darurat",
    "industrydata.life.features.03.desc": "Broadcast bencana, informasi cuaca, dan kampanye kesehatan.",
    "industrydata.life.illustrationtitle": "Public Utility & Assistance Hub",
    "hero.span.text-001": "Next-Generation AI CRM",
    "hero.h1.text-001": "Sobot.io – All In One",
    "hero.span.text-002": "CRM Omnichannel",
    "hero.p.text-001": "Otomatiskan layanan pelanggan, tingkatkan efisiensi operasional, dan pangkas biaya operasional hingga",
    "hero.span.text-003": "50%",
    "hero.p.text-002": "dengan dukungan sertifikasi ISO 27001, ISO 9001, kepatuhan GDPR, serta terdaftar resmi PSE Kominfo.",
    "hero.link.href-001": "/contact",
    "hero.span.text-004": "Free Consultation Now",
    "hero.span.text-005": "ISO 27001 & PSE Kominfo",
    "contact.p.text-003": "99.9%",
    "contact.p.text-004": "Uptime Guarantee",
    "contact.p.text-005": "< 0.2s",
    "contact.p.text-006": "AI Latency SLA",
    "contact.p.text-007": "50%",
    "contact.p.text-008": "Cost Saving",
    "contact.div.text-001": "S",
    "contact.h3.text-001": "Sobot AI Hub",
    "contact.p.text-009": "Pilih channel di bawah untuk simulasi:",
    "contact.span.text-006": "Online",
    "contact.div.text-002": "Kanal Aktif:",
    "contact.span.text-007": "Sobot AI Agent",
    "contact.span.text-008": "Respon 0.1s",
    "security.span.text-009": "End-to-End Encrypted & GDPR Compliant",
    "features.span.text-010": "Core Intelligence",
    "features.h2.text-001": "3 Pilar Utama Teknologi AI Sobot",
    "features.p.text-010": "Solusi otomatisasi lengkap berbasis AI untuk percakapan teks, pesan terstruktur, hingga panggilan suara.",
    "features.span.text-011": "Lihat Detail Fitur",
    "industries.span.text-012": "Tailored By Industry",
    "industries.h2.text-002": "Solusi CRM Berdasarkan Sektor Industri",
    "industries.p.text-011": "Dioptimalkan untuk alur kerja dan kepatuhan spesifik pada sektor bisnis Anda.",
    "industries.input.placeholder-001": "Cari fitur industri...",
    "industries.p.text-012": "Tidak ada fitur yang cocok dengan kata kunci pencarian.",
    "features.p.text-013": "Siap diintegrasikan langsung dengan sistem CRM, Database internal, & API eksisting bisnis Anda secara aman.",
    "features.link.href-002": "/contact",
    "features.span.text-013": "Minta Demo Khusus Industri Ini",
      "cards.dataset-01.wa.label": "WA",
    "cards.dataset-01.ig.label": "IG",
    "cards.dataset-01.web.label": "Web",
    "cards.dataset-01.voice.label": "Voice",
    "cards.dataset-02.agent.title": "AI Agent (LLM)",
    "cards.dataset-02.agent.desc": "Memahami bahasa alami kompleks (NLU), melayani penjualan dan customer support 24/7 tanpa halusinasi.",
    "cards.dataset-02.agent.badge": "Generative AI",
    "cards.dataset-02.chatbot.title": "Rule & Flow Chatbot",
    "cards.dataset-02.chatbot.desc": "Alur percakapan terstruktur presisi tinggi untuk penanganan FAQ, pengumpulan data form, dan ticketing.",
    "cards.dataset-02.chatbot.badge": "Workflow Bot",
    "cards.dataset-02.voice.title": "Voice AI Calling",
    "cards.dataset-02.voice.desc": "Melakukan panggilan suara alami (inbound & outbound) dengan kemampuan transfer langsung ke agen manusia.",
    "cards.dataset-02.voice.badge": "Real-Time Voice",
    "cards.dataset-03.retail.label": "Retail & E-commerce",
    "cards.dataset-03.financial.label": "Financial Services",
    "cards.dataset-03.gaming.label": "Gaming",
    "cards.dataset-03.education.label": "Education",
    "cards.dataset-03.enterprise.label": "Enterprise",
    "cards.dataset-03.life.label": "Public Services",
},
  "solutions-workspace": {
    "plans.starter.name": "Business Starter",
    "plans.starter.tagline": "Ideal untuk tim berkembang yang butuh email domain profesional.",
    "plans.starter.monthlyprice": "110",
    "plans.starter.annualprice": "90",
    "plans.starter.features.01": "30 GB Storage per user",
    "plans.starter.features.02": "Email Bisnis Kustom (@domain.com)",
    "plans.starter.features.03": "Video Conference hingga 100 Peserta",
    "plans.starter.features.04": "Standard Security & Admin Controls",
    "plans.starter.features.05": "Dukungan Teknis 24/7",
    "plans.standard.name": "Business Standard",
    "plans.standard.tagline": "Pilihan paling populer dengan kapasitas lega & rekam rapat.",
    "plans.standard.monthlyprice": "220",
    "plans.standard.annualprice": "180",
    "plans.standard.features.01": "2 TB Storage Pooled per user",
    "plans.standard.features.02": "Rekam Rapat Video ke Google Drive",
    "plans.standard.features.03": "Shared Drives untuk Kolaborasi Tim",
    "plans.standard.features.04": "Pencarian Canggih dengan Cloud Search",
    "plans.standard.features.05": "DLP & Keamanan Tingkat Menengah",
    "plans.plus.name": "Business Plus",
    "plans.plus.tagline": "Fitur keamanan ekstra, eDiscovery, & kontrol endpoint lanjutan.",
    "plans.plus.monthlyprice": "330",
    "plans.plus.annualprice": "270",
    "plans.plus.features.01": "5 TB Storage Pooled per user",
    "plans.plus.features.02": "Rapat Video hingga 500 Peserta + Absensi",
    "plans.plus.features.03": "Vault untuk eDiscovery & Retensi Data",
    "plans.plus.features.04": "Context-Aware Access Control",
    "plans.plus.features.05": "Advanced Endpoint Management",
    "plans.enterprise.name": "Enterprise",
    "plans.enterprise.tagline": "Solusi skala besar tanpa batas kapasitas & proteksi S/MIME.",
    "plans.enterprise.monthlyprice": "450",
    "plans.enterprise.annualprice": "380",
    "plans.enterprise.features.01": "Penyimpanan Fleksibel (Uncapped)",
    "plans.enterprise.features.02": "S/MIME Data Encryption",
    "plans.enterprise.features.03": "Integrasi AppSheet Core Level Perusahaan",
    "plans.enterprise.features.04": "Noise Cancellation Canggih saat Meet",
    "plans.enterprise.features.05": "Priority Premier Enterprise Support",
    "appfeatures.0.name": "Gmail for Business",
    "appfeatures.0.desc": "Email domain profesional anti-spam dengan integrasi AI, smart reply, & keamanan tingkat lanjut.",
    "appfeatures.0.badge": "Communication",
    "appfeatures.1.name": "Google Meet",
    "appfeatures.1.desc": "Rapat video HD hingga ratusan peserta, rekam otomatis, pembatalan bising, & live transcription.",
    "appfeatures.1.badge": "Video Conference",
    "appfeatures.2.name": "Google Drive",
    "appfeatures.2.desc": "Penyimpanan cloud terpusat, kontrol akses bertingkat, & kemudahan berbagi antar divisi.",
    "appfeatures.2.badge": "Cloud Storage",
    "appfeatures.3.name": "Docs, Sheets, Slides",
    "appfeatures.3.desc": "Kolaborasi dokumen real-time tanpa resiko tumpang tindih data. Edit bersama secara transparan.",
    "appfeatures.3.badge": "Productivity Suite",
    "hero.span.text-001": "Official Google Cloud Premier Partner",
    "hero.h1.text-001": "Google Workspace",
    "hero.span.text-002": "For Enterprise Scaling",
    "hero.p.text-001": "Tingkatkan produktivitas tim dengan email domain resmi, kolaborasi cloud tanpa hambatan, serta proteksi keamanan setingkat bank. Termasuk sertifikasi ISO 27001 dan dukungan tim teknis lokal.",
    "hero.link.href-001": "/contact",
    "hero.span.text-003": "Free Consultation Now",
    "hero.link.href-002": "#plans",
    "hero.span.text-004": "Lihat Simulasi Paket",
    "hero.p.text-002": "99.9%",
    "hero.p.text-003": "Uptime Guarantee SLA",
    "hero.p.text-004": "0%",
    "hero.p.text-005": "Downtime Migration",
    "hero.p.text-006": "24/7",
    "hero.p.text-007": "Local Tech Support",
    "hero.h3.text-001": "Google Workspace",
    "hero.p.text-008": "Cloud Enterprise Infrastructure",
    "hero.span.text-005": "Verified",
    "security.span.text-006": "ISO 27001 & SOC 2/3 Compliant",
    "security.span.text-007": "100% Safe",
    "security.span.text-008": "Pilar Solusi",
    "security.h2.text-001": "4 Fondasi Kolaborasi Modern",
    "security.span.text-009": "Aplikasi Ekosistem",
    "security.h2.text-002": "Everything your team needs",
    "security.p.text-009": "Pilih aplikasi untuk melihat kemampuan integrasi dan fitur spesifik.",
    "security.span.text-010": "Included in Plan",
    "pricing.span.text-011": "Kalkulator & Paket Resmi",
    "pricing.h2.text-003": "Google Workspace Plans",
    "pricing.p.text-010": "Pilih paket yang sesuai dengan skala tim, kebutuhan penyimpanan, dan kebijakan privasi Anda.",
    "pricing.span.text-012": "Bulanan",
    "pricing.span.text-013": "Tahunan",
    "pricing.span.text-014": "Hemat 18%",
    "pricing.span.text-015": "Simulasi Jumlah User:",
    "pricing.span.text-016": "Lisensi",
    "pricing.span.text-017": "Most Popular",
    "pricing.p.text-011": "Estimasi Biaya (",
    "pricing.p.text-012": "User):",
    "pricing.p.text-013": "Rp",
    "pricing.p.text-014": "k",
    "pricing.span.text-018": "/bln",
    "pricing.p.text-015": "@ Rp",
    "pricing.p.text-016": "k / user / bulan",
    "pricing.span.text-019": "Request Official Quote",
    "architecture.span.text-020": "Smooth Cutover",
    "architecture.h2.text-004": "Zero Downtime Migration Service",
    "architecture.p.text-017": "Pindahkan seluruh data email, kalender, kontak, & file dokumen dari platform lama (Microsoft 365, IMAP, cPanel, dll) secara aman tanpa ada email yang hilang.",
    "architecture.h3.text-002": "Migration Ready Portal",
    "architecture.p.text-018": "Sistem migrasi otomatis berbasis Google Cloud Migration Tools untuk keandalan 100%.",
    "architecture.span.text-021": "Data Integrity Guarantee",
    "architecture.h4.text-001": "Identity & Access",
    "architecture.p.text-019": "SSO/OAuth, MFA, Context-Aware Access, serta kontrol granular per-OU/Group.",
    "architecture.h4.text-002": "Data Protection",
    "architecture.p.text-020": "DLP untuk Gmail/Drive, pelabelan data sensitif, Vault audit, & eDiscovery.",
    "architecture.h4.text-003": "Operational Security",
    "architecture.p.text-021": "Alert Center real-time, ekspor log ke SIEM, & audit Endpoint Management.",
    "cta.span.text-022": "Certified Partner Deployment",
    "cta.h2.text-005": "Siap Modernisasi",
    "cta.span.text-023": "Cara Kerja Tim Anda?",
    "cta.p.text-022": "Konsultasikan struktur lisensi, perencanaan migrasi, dan pelatihan pengguna dengan konsultan ahli kami secara gratis.",
    "cta.link.href-003": "/contact",
    "cta.link.text-001": "Hubungi Konsultan Sekarang",
    "cta.img.alt-001": "Google Workspace Partner Representative",
    "cta.span.text-024": "Tim Konsultan Resmi",
    "cta.span.text-025": "★ 4.9/5 SLA Rating",
      "cards.dataset-01.01.title": "Email Domain Resmi",
    "cards.dataset-01.02.title": "Google Meet Enterprise",
    "cards.dataset-01.03.title": "Unlimited Shared Drive",
    "cards.dataset-02.01.title": "Email Bisnis",
    "cards.dataset-02.01.desc": "@domain Anda dengan proteksi spam, phishing, dan malware otomatis.",
    "cards.dataset-02.02.title": "Meet & Chat",
    "cards.dataset-02.02.desc": "Rapat video 1 klik, rekam otomatis, noise cancel, & breakout rooms.",
    "cards.dataset-02.03.title": "Drive & Shared Drive",
    "cards.dataset-02.03.desc": "Penyimpanan terpusat aman, akses berbasis otorisasi, & audit trail lengkap.",
    "cards.dataset-02.04.title": "Keamanan & Admin",
    "cards.dataset-02.04.desc": "2-Step Verification, DLP, Context-Aware Access, Vault & eDiscovery.",
    "cards.dataset-03.all.label": "Semua Aplikasi",
    "cards.dataset-03.email.label": "Gmail",
    "cards.dataset-03.meet.label": "Google Meet",
    "cards.dataset-03.drive.label": "Drive",
    "cards.dataset-03.security.label": "Docs Suite",
    "cards.dataset-04.01.title": "Assessment",
    "cards.dataset-04.01.desc": "Audit domain & rencana migrasi data",
    "cards.dataset-04.02.title": "Proof-of-Concept",
    "cards.dataset-04.02.desc": "Uji coba pilot pada subset user",
    "cards.dataset-04.03.title": "Cutover Sync",
    "cards.dataset-04.03.desc": "Sinkronisasi latar belakang & DNS",
    "cards.dataset-04.04.title": "Training & Support",
    "cards.dataset-04.04.desc": "Pendampingan pengguna pasca-migrasi",
},
};
