import type { PageContentMap } from "@/lib/page-content-types";

export const MAIN_PAGE_CONTENT_DEFAULTS: PageContentMap = {
  home: {
    "home.hero-section.text.enterprise-managed-services-talent-solutions": "Enterprise Managed Services & Talent Solutions",
    "home.hero-section.text.for-your-business-growth": "for Your Business Growth\r",
    "home.hero-section.text.prima-services-membantu-enterprise-dan-bisnis-be": "Prima Services membantu enterprise dan bisnis berkembang di Indonesia mengakselerasi operasional dengan solusi terintegrasi, aman, dan berstandar global.\r",
    "home.hero-section.href.contact": "/contact",
    "home.hero-section.text.get-free-consultation": "Get Free Consultation",
    "home.hero-section.text.iso-certified": "ISO Certified",
    "home.hero-section.text.24-7-sla": "24/7 SLA",
    "home.hero-section.text.efficiency": "Efficiency",
    "home.hero-section.text.45-growth": "+45% Growth",
    "home.hero-section.text.status": "Status",
    "home.hero-section.text.24-7-active-sla": "24/7 Active SLA",
    "home.hero-section.text.button": "button",
    "home.hero-section.text.w-8-bg-blue-600": "w-8 bg-blue-600",
    "home.hero-section.text.w-2-bg-slate-300-hover-bg-slate-400": "w-2 bg-slate-300 hover:bg-slate-400",
    "home.our-services-section.text.what-we-offer": "What We Offer\r",
    "home.our-services-section.text.our-services": "OUR SERVICES\r",
    "home.our-services-section.text.solusi-operasional-terpadu-dan-manajemen-talenta": "Solusi operasional terpadu dan manajemen talenta yang dirancang untuk mempercepat skala bisnis Anda.\r",
    "home.our-services-section.text.core-offering": "Core Offering\r",
    "home.our-services-section.aria-label.toggle-details": "Toggle Details",
    "home.our-services-section.text.pt-6-space-y-6-animate-in-fade-in-slide-in-from-": "pt-6 space-y-6 animate-in fade-in slide-in-from-top-4 duration-300",
    "home.our-services-section.text.text-xs-font-black-uppercase-tracking-widest-tex": "text-xs font-black uppercase tracking-widest text-slate-400 mb-2 flex items-center gap-2",
    "home.our-services-section.text.w-4-h-4-text-amber-500-fill-amber-500-animate-pu": "w-4 h-4 text-amber-500 fill-amber-500 animate-pulse",
    "home.our-services-section.text.p-5-rounded-2xl-bg-white-90-backdrop-blur-md-bor": "p-5 rounded-2xl bg-white/90 backdrop-blur-md border border-slate-200/80 shadow-xs",
    "home.our-services-section.text.text-sm-md-text-base-text-slate-600-leading-rela": "text-sm md:text-base text-slate-600 leading-relaxed font-normal",
    "home.our-services-section.text.pt-4-border-t-border-slate-200-80-space-y-4": "pt-4 border-t border-slate-200/80 space-y-4",
    "home.our-services-section.text.text-xs-font-black-uppercase-tracking-widest-tex-2": "text-xs font-black uppercase tracking-widest text-slate-400",
    "home.our-services-section.text.grid-grid-cols-1-md-grid-cols-3-gap-6": "grid grid-cols-1 md:grid-cols-3 gap-6",
    "home.our-services-section.text.bg-white-rounded-2xl-overflow-hidden-border-bord": "bg-white rounded-2xl overflow-hidden border border-slate-200/90 shadow-xs hover:shadow-2xl hover:border-blue-300 hover:-translate-y-2 transition-all duration-300 flex flex-col justify-between group/card",
    "home.our-services-section.text.relative-w-full-h-40-bg-slate-100-overflow-hidde": "relative w-full h-40 bg-slate-100 overflow-hidden",
    "home.our-services-section.text.object-cover-group-hover-card-scale-110-transiti": "object-cover group-hover/card:scale-110 transition-transform duration-700",
    "home.our-services-section.text.p-5-border-b-border-slate-100": "p-5 border-b border-slate-100",
    "home.our-services-section.text.font-extrabold-text-slate-900-text-base-leading-": "font-extrabold text-slate-900 text-base leading-snug group-hover/card:text-blue-600 transition-colors mb-1.5",
    "home.our-services-section.text.text-xs-text-slate-500-leading-relaxed": "text-xs text-slate-500 leading-relaxed",
    "home.our-services-section.text.p-5-bg-slate-50-50": "p-5 bg-slate-50/50",
    "home.our-services-section.text.text-10px-font-bold-uppercase-tracking-wider-tex": "text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-2",
    "home.our-services-section.text.space-y-2": "space-y-2",
    "home.our-services-section.text.flex-items-start-gap-2-text-xs-font-medium-text-": "flex items-start gap-2 text-xs font-medium text-slate-700",
    "home.our-services-section.text.w-1-5-h-1-5-rounded-full-bg-blue-600-mt-1-5-shri": "w-1.5 h-1.5 rounded-full bg-blue-600 mt-1.5 shrink-0",
    "home.our-services-section.text.leading-snug": "leading-snug",
    "home.our-services-section.text.overview-capabilities": "OVERVIEW & CAPABILITIES",
    "home.our-services-section.text.our-bpo-solutions-services": "OUR BPO SOLUTIONS & SERVICES:\r",
    "home.our-services-section.text.bg-white-rounded-2xl-overflow-hidden-border-bord-2": "bg-white rounded-2xl overflow-hidden border border-slate-200/90 shadow-xs hover:shadow-2xl hover:border-blue-300 hover:-translate-y-2 transition-all duration-300 flex flex-col justify-between group/card",
    "home.our-services-section.text.relative-w-full-h-40-bg-slate-100-overflow-hidde-2": "relative w-full h-40 bg-slate-100 overflow-hidden",
    "home.our-services-section.text.object-cover-group-hover-card-scale-110-transiti-2": "object-cover group-hover/card:scale-110 transition-transform duration-700",
    "home.our-services-section.text.p-5-border-b-border-slate-100-2": "p-5 border-b border-slate-100",
    "home.our-services-section.text.font-extrabold-text-slate-900-text-base-leading--2": "font-extrabold text-slate-900 text-base leading-snug group-hover/card:text-blue-600 transition-colors mb-1.5",
    "home.our-services-section.text.text-xs-text-slate-500-leading-relaxed-2": "text-xs text-slate-500 leading-relaxed",
    "home.our-services-section.text.p-5-bg-slate-50-50-2": "p-5 bg-slate-50/50",
    "home.our-services-section.text.text-10px-font-bold-uppercase-tracking-wider-tex-2": "text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-2",
    "home.our-services-section.text.space-y-2-2": "space-y-2",
    "home.our-services-section.text.flex-items-start-gap-2-text-xs-font-medium-text--2": "flex items-start gap-2 text-xs font-medium text-slate-700",
    "home.our-services-section.text.w-1-5-h-1-5-rounded-full-bg-blue-600-mt-1-5-shri-2": "w-1.5 h-1.5 rounded-full bg-blue-600 mt-1.5 shrink-0",
    "home.our-services-section.text.leading-snug-2": "leading-snug",
    "home.our-services-section.text.key-offerings": "Key Offerings:\r",
    "home.our-services-section.text.flex-items-start-gap-2-text-xs-font-medium-text--3": "flex items-start gap-2 text-xs font-medium text-slate-700",
    "home.our-services-section.text.w-1-5-h-1-5-rounded-full-bg-blue-600-mt-1-5-shri-3": "w-1.5 h-1.5 rounded-full bg-blue-600 mt-1.5 shrink-0",
    "home.our-services-section.text.leading-snug-3": "leading-snug",
    "home.our-services-section.text.show-less": "Show Less",
    "home.our-services-section.text.explore-capabilities": "Explore Capabilities",
    "home.bpo-capabilities-section.text.operational-excellence": "Operational Excellence\r",
    "home.bpo-capabilities-section.text.business-process-outsourcing-bpo": "Business Process Outsourcing (BPO)\r",
    "home.bpo-capabilities-section.text.teknologi-dan-infrastruktur-operasional-terdedik": "Teknologi dan infrastruktur operasional terdedikasi untuk skalabilitas bisnis.\r",
    "home.bpo-capabilities-section.text.bg-white-rounded-3xl-p-6-text-center-border-bord": "bg-white rounded-3xl p-6 text-center border border-slate-200/90 shadow-sm hover:shadow-2xl hover:border-blue-400 hover:-translate-y-2 transition-all duration-500 group flex flex-col items-center relative overflow-hidden",
    "home.bpo-capabilities-section.text.absolute-top-0-right-0-w-20-h-20-bg-gradient-to-": "absolute top-0 right-0 w-20 h-20 bg-gradient-to-bl from-blue-500/10 to-transparent rounded-bl-full pointer-events-none group-hover:scale-125 transition-transform duration-500",
    "home.bpo-capabilities-section.text.relative-w-20-h-20-mb-4-group-hover-scale-110-gr": "relative w-20 h-20 mb-4 group-hover:scale-110 group-hover:rotate-3 transition-transform duration-500",
    "home.bpo-capabilities-section.text.object-contain": "object-contain",
    "home.bpo-capabilities-section.text.font-extrabold-text-slate-900-text-base-mb-1-5-w": "font-extrabold text-slate-900 text-base mb-1.5 whitespace-pre-line group-hover:text-blue-600 transition-colors leading-snug",
    "home.bpo-capabilities-section.text.text-xs-text-slate-500-leading-relaxed-font-norm": "text-xs text-slate-500 leading-relaxed font-normal",
    "home.how-we-control-enable-section.text.governance-quality-assurance": "Governance & Quality Assurance",
    "home.how-we-control-enable-section.text.how-we-control": "How We Control ",
    "home.how-we-control-enable-section.text.playbooks-governance": "(Playbooks & Governance)",
    "home.how-we-control-enable-section.text.kami-menyediakan-standar-operasional-fleksibel-b": "Kami menyediakan standar operasional fleksibel berbasis SLA, QA terukur, dan pemantauan berkala.\r",
    "home.how-we-control-enable-section.text.group-relative-bg-slate-50-70-border-border-slat": "group relative bg-slate-50/70 border border-slate-200/90 rounded-3xl p-6 transition-all duration-500 hover:-translate-y-2 hover:bg-white hover:shadow-2xl hover:border-blue-300 flex flex-col justify-between overflow-hidden shadow-xs",
    "home.how-we-control-enable-section.text.flex-items-center-justify-between-mb-4": "flex items-center justify-between mb-4",
    "home.how-we-control-enable-section.text.w-6-h-6-stroke-1-8": "w-6 h-6 stroke-[1.8]",
    "home.how-we-control-enable-section.text.text-xs-font-black-text-slate-300-group-hover-te": "text-xs font-black text-slate-300 group-hover:text-blue-600 transition-colors",
    "home.how-we-control-enable-section.text.text-base-font-black-text-slate-900-mb-2-group-h": "text-base font-black text-slate-900 mb-2 group-hover:text-blue-600 transition-colors",
    "home.how-we-control-enable-section.text.text-xs-sm-text-sm-text-slate-500-leading-relaxe": "text-xs sm:text-sm text-slate-500 leading-relaxed font-normal",
    "home.how-we-control-enable-section.text.mt-6-pt-3-border-t-border-slate-200-60-flex-item": "mt-6 pt-3 border-t border-slate-200/60 flex items-center justify-between text-xs font-extrabold text-slate-400 group-hover:text-blue-600 transition-colors",
    "home.how-we-control-enable-section.text.w-4-h-4-group-hover-translate-x-1-5-transition-t": "w-4 h-4 group-hover:translate-x-1.5 transition-transform",
    "home.how-we-control-enable-section.text.0": "0",
    "home.how-we-control-enable-section.text.standards-verified": "Standards Verified",
    "home.how-we-control-enable-section.text.integrated-tech-stack": "Integrated Tech Stack",
    "home.how-we-control-enable-section.text.how-we-enable": "How We Enable ",
    "home.how-we-control-enable-section.text.tools-integrations": "(Tools & Integrations)",
    "home.how-we-control-enable-section.text.group-relative-bg-slate-50-60-hover-bg-white-rou": "group relative bg-slate-50/60 hover:bg-white rounded-2xl p-4 md:px-6 md:py-4 flex flex-col md:flex-row items-center justify-between gap-4 border border-slate-200/90 shadow-xs hover:shadow-xl hover:border-blue-300 hover:-translate-y-1 transition-all duration-300 overflow-hidden",
    "home.how-we-control-enable-section.text.flex-items-center-gap-4-w-full-md-w-auto": "flex items-center gap-4 w-full md:w-auto",
    "home.how-we-control-enable-section.text.w-12-h-12-rounded-xl-bg-white-border-border-slat": "w-12 h-12 rounded-xl bg-white border border-slate-200/90 flex items-center justify-center shrink-0 p-2 shadow-sm group-hover:scale-110 transition-transform",
    "home.how-we-control-enable-section.text.object-contain": "object-contain",
    "home.how-we-control-enable-section.text.text-base-font-extrabold-text-slate-900-group-ho": "text-base font-extrabold text-slate-900 group-hover:text-blue-600 transition-colors leading-tight",
    "home.how-we-control-enable-section.text.text-xs-text-slate-500-mt-0-5-font-medium": "text-xs text-slate-500 mt-0.5 font-medium",
    "home.how-we-control-enable-section.text.w-full-md-w-auto-shrink-0": "w-full md:w-auto shrink-0",
    "home.how-we-control-enable-section.text.inline-flex-items-center-justify-center-gap-2-bg": "inline-flex items-center justify-center gap-2 bg-blue-50 border border-blue-200/80 px-4 py-2 rounded-full text-xs font-bold text-blue-700 shadow-xs group-hover:bg-blue-600 group-hover:text-white transition-all duration-300",
    "home.how-we-control-enable-section.text.w-3-5-h-3-5-text-amber-500-group-hover-text-ambe": "w-3.5 h-3.5 text-amber-500 group-hover:text-amber-300",
    "home.recruitment-rpo-section.text.end-to-end-talent-acquisition": "End-to-End Talent Acquisition",
    "home.recruitment-rpo-section.text.how-we-recruit": "How We Recruit ",
    "home.recruitment-rpo-section.text.rpo-process": "(RPO Process)",
    "home.recruitment-rpo-section.alt.prima-services-logo": "Prima Services Logo",
    "home.recruitment-rpo-section.text.group-relative-bg-white-text-slate-900-rounded-3": "group relative bg-white text-slate-900 rounded-3xl p-6 shadow-sm border border-slate-200/90 transition-all duration-500 hover:-translate-y-2 hover:shadow-2xl hover:border-blue-300 flex flex-col justify-between overflow-hidden",
    "home.recruitment-rpo-section.text.flex-items-center-justify-between-mb-4": "flex items-center justify-between mb-4",
    "home.recruitment-rpo-section.text.text-10px-font-black-tracking-wider-uppercase-px": "text-[10px] font-black tracking-wider uppercase px-3 py-0.5 rounded-full bg-blue-50 text-blue-600 border border-blue-200/90",
    "home.recruitment-rpo-section.text.text-2xl-font-black-text-slate-200-group-hover-t": "text-2xl font-black text-slate-200 group-hover:text-blue-600 transition-colors",
    "home.recruitment-rpo-section.text.relative-w-full-h-40-mb-4-rounded-2xl-overflow-h": "relative w-full h-40 mb-4 rounded-2xl overflow-hidden bg-slate-100 border border-slate-200/80 shadow-inner group/img",
    "home.recruitment-rpo-section.text.object-cover-transition-transform-duration-700-g": "object-cover transition-transform duration-700 group-hover/img:scale-110",
    "home.recruitment-rpo-section.text.text-base-font-black-text-slate-900-mb-1-group-h": "text-base font-black text-slate-900 mb-1 group-hover:text-blue-600 transition-colors leading-snug",
    "home.recruitment-rpo-section.text.text-xs-text-slate-500-leading-relaxed-font-norm": "text-xs text-slate-500 leading-relaxed font-normal mb-4",
    "home.recruitment-rpo-section.text.pt-4-border-t-border-slate-100-bg-slate-50-60-gr": "pt-4 border-t border-slate-100 bg-slate-50/60 group-hover:bg-blue-50/30 -mx-6 -mb-6 p-6 transition-colors",
    "home.recruitment-rpo-section.text.text-10px-font-bold-uppercase-tracking-wider-tex": "text-[10px] font-bold uppercase tracking-wider text-slate-400 mb-2",
    "home.recruitment-rpo-section.text.space-y-2-text-xs-text-slate-700-font-medium": "space-y-2 text-xs text-slate-700 font-medium",
    "home.recruitment-rpo-section.text.flex-items-start-gap-2": "flex items-start gap-2",
    "home.recruitment-rpo-section.text.w-1-5-h-1-5-rounded-full-bg-blue-600-mt-1-5-shri": "w-1.5 h-1.5 rounded-full bg-blue-600 mt-1.5 shrink-0",
    "home.recruitment-rpo-section.text.leading-snug": "leading-snug",
    "home.recruitment-rpo-section.text.service-0": "SERVICE 0",
    "home.recruitment-rpo-section.text.0": "0",
    "home.recruitment-rpo-section.text.key-deliverables": "Key Deliverables:",
    "home.recruitment-rpo-section.text.flex-items-start-gap-2-2": "flex items-start gap-2",
    "home.recruitment-rpo-section.text.w-1-5-h-1-5-rounded-full-bg-blue-600-mt-1-5-shri-2": "w-1.5 h-1.5 rounded-full bg-blue-600 mt-1.5 shrink-0",
    "home.recruitment-rpo-section.text.leading-snug-2": "leading-snug",
    "home.how-we-scale-section.text.scalable-operation-framework": "Scalable Operation Framework",
    "home.how-we-scale-section.text.how-we-scale": "How We Scale ",
    "home.how-we-scale-section.text.outsourcing-services": "(Outsourcing Services)",
    "home.how-we-scale-section.text.merancang-menjalankan-dan-mengoptimalkan-operasi": "Merancang, menjalankan, dan mengoptimalkan operasional bisnis Anda secara fleksibel baik on-site maupun remote.\r",
    "home.how-we-scale-section.alt.prima-services-logo": "Prima Services Logo",
    "home.how-we-scale-section.text.bg-slate-50-70-hover-bg-white-border-border-slat": "bg-slate-50/70 hover:bg-white border border-slate-200/90 hover:border-blue-300 rounded-3xl p-5 transition-all duration-300 hover:-translate-y-2 hover:shadow-2xl flex flex-col justify-between group shadow-xs relative",
    "home.how-we-scale-section.text.flex-items-center-justify-between-mb-3": "flex items-center justify-between mb-3",
    "home.how-we-scale-section.text.text-10px-font-extrabold-uppercase-tracking-wide": "text-[10px] font-extrabold uppercase tracking-wider text-blue-600 bg-blue-100/80 px-2 py-0.5 rounded-md border border-blue-200",
    "home.how-we-scale-section.text.text-lg-font-black-text-slate-300-group-hover-te": "text-lg font-black text-slate-300 group-hover:text-blue-600 transition-colors",
    "home.how-we-scale-section.text.relative-w-full-h-32-mb-4-rounded-2xl-bg-white-b": "relative w-full h-32 mb-4 rounded-2xl bg-white border border-slate-200/80 p-3 flex items-center justify-center group-hover:bg-blue-50/40 transition-colors",
    "home.how-we-scale-section.text.object-contain-p-2-group-hover-scale-110-transit": "object-contain p-2 group-hover:scale-110 transition-transform duration-500",
    "home.how-we-scale-section.text.text-center-pt-2-border-t-border-slate-200-80": "text-center pt-2 border-t border-slate-200/80",
    "home.how-we-scale-section.text.text-xs-sm-text-sm-font-black-text-slate-900-gro": "text-xs sm:text-sm font-black text-slate-900 group-hover:text-blue-600 transition-colors leading-snug",
    "home.how-we-deliver-section.text.step-by-step-execution": "Step-by-Step Execution\r",
    "home.how-we-deliver-section.text.how-we-deliver": "How We Deliver ",
    "home.how-we-deliver-section.text.outsourcing-flow": "(Outsourcing Flow)",
    "home.how-we-deliver-section.text.proses-alur-kerja-yang-terstruktur-dan-terukur-u": "Proses alur kerja yang terstruktur dan terukur untuk memastikan efisiensi optimal.\r",
    "home.how-we-deliver-section.text.bg-white-border-border-slate-200-90-hover-border": "bg-white border border-slate-200/90 hover:border-blue-300 rounded-3xl p-5 transition-all duration-300 hover:-translate-y-2 hover:shadow-2xl flex flex-col justify-between group shadow-xs",
    "home.how-we-deliver-section.text.flex-items-center-justify-between-mb-4": "flex items-center justify-between mb-4",
    "home.how-we-deliver-section.text.w-12-h-12-rounded-2xl-bg-blue-50-80-border-borde": "w-12 h-12 rounded-2xl bg-blue-50/80 border border-blue-100 p-2 flex items-center justify-center shrink-0 shadow-xs group-hover:scale-110 group-hover:rotate-6 transition-all",
    "home.how-we-deliver-section.text.object-contain": "object-contain",
    "home.how-we-deliver-section.text.text-xl-font-black-text-slate-300-group-hover-te": "text-xl font-black text-slate-300 group-hover:text-blue-600 transition-colors",
    "home.how-we-deliver-section.text.text-sm-font-bold-text-slate-900-group-hover-tex": "text-sm font-bold text-slate-900 group-hover:text-blue-600 transition-colors leading-snug mb-1.5",
    "home.how-we-deliver-section.text.text-xs-text-slate-500-leading-relaxed-font-norm": "text-xs text-slate-500 leading-relaxed font-normal",
    "home.how-we-deliver-section.text.mt-4-pt-2-5-border-t-border-slate-100-flex-items": "mt-4 pt-2.5 border-t border-slate-100 flex items-center justify-end text-[11px] text-blue-600 font-extrabold",
    "home.how-we-deliver-section.text.w-3-5-h-3-5-group-hover-translate-x-1-5-transiti": "w-3.5 h-3.5 group-hover:translate-x-1.5 transition-transform",
    "home.global-relations-section.text.global-relations-expansion": "GLOBAL RELATIONS & EXPANSION",
    "home.global-relations-section.text.international": "International ",
    "home.global-relations-section.text.partnerships-expansion": "Partnerships & Expansion\r",
    "home.global-relations-section.text.akselerasi-jangkauan-bisnis-anda-ke-pasar-global": "Akselerasi jangkauan bisnis Anda ke pasar global dengan dukungan konsultasi regulasi, pemetaan jaringan lokal, dan kemitraan strategis.\r",
    "home.global-relations-section.text.group-relative-p-3-5-rounded-2xl-bg-white-border": "group relative p-3.5 rounded-2xl bg-white border border-slate-200/80 shadow-xs hover:shadow-md hover:border-blue-300 transition-all duration-300 flex items-start gap-3.5 overflow-hidden",
    "home.global-relations-section.text.absolute-left-0-top-0-bottom-0-w-1-bg-gradient-t": "absolute left-0 top-0 bottom-0 w-1 bg-gradient-to-b from-blue-500 to-indigo-600 opacity-0 group-hover:opacity-100 transition-opacity duration-300",
    "home.global-relations-section.text.w-8-h-8-rounded-xl-bg-slate-100-group-hover-bg-b": "w-8 h-8 rounded-xl bg-slate-100 group-hover:bg-blue-600 text-slate-600 group-hover:text-white flex items-center justify-center shrink-0 font-bold text-xs transition-colors duration-300 shadow-xs",
    "home.global-relations-section.text.space-y-0-5-pt-0-5": "space-y-0.5 pt-0.5",
    "home.global-relations-section.text.text-xs-sm-text-sm-font-medium-text-slate-700-gr": "text-xs sm:text-sm font-medium text-slate-700 group-hover:text-slate-900 leading-snug transition-colors",
    "home.global-relations-section.text.0": "0",
    "home.global-relations-section.alt.global-world-map": "Global World Map",
    "home.global-relations-section.text.network": "Network",
    "home.global-relations-section.text.50-global-partners": "50+ Global Partners",
    "home.global-relations-section.text.compliance": "Compliance",
    "home.global-relations-section.text.100-regulated": "100% Regulated",
    "home.how-we-enable-global-growth.text.end-to-end-methodology": "End-to-End Methodology\r",
    "home.how-we-enable-global-growth.text.how-we-enable": "How We Enable ",
    "home.how-we-enable-global-growth.text.global-growth": "Global Growth",
    "home.how-we-enable-global-growth.text.metodologi-terstruktur-untuk-mendukung-akseleras": "Metodologi terstruktur untuk mendukung akselerasi bisnis ke ranah global secara berkelanjutan.\r",
    "home.how-we-enable-global-growth.text.flex-items-center-justify-between-mb-4": "flex items-center justify-between mb-4",
    "home.how-we-enable-global-growth.text.w-4-h-4-stroke-1-8": "w-4 h-4 stroke-[1.8]",
    "home.how-we-enable-global-growth.text.text-amber-300-font-black-flex-items-center-gap-": "text-amber-300 font-black flex items-center gap-1.5 animate-pulse",
    "home.how-we-enable-global-growth.text.w-4-h-4-text-amber-300-fill-amber-300-20": "w-4 h-4 text-amber-300 fill-amber-300/20",
    "home.how-we-enable-global-growth.text.step": "STEP ",
    "home.how-we-enable-global-growth.text.text-amber-300-font-black-flex-items-center-gap--2": "text-amber-300 font-black flex items-center gap-1.5 animate-pulse",
    "home.how-we-enable-global-growth.text.w-4-h-4-text-amber-300-fill-amber-300-20-2": "w-4 h-4 text-amber-300 fill-amber-300/20",
    "home.how-we-enable-global-growth.text.active": "Active\r",
    "home.portfolio-section.text.showcase-works": "Showcase & Works\r",
    "home.portfolio-section.text.our-portfolios": "Our Portfolios\r",
    "home.portfolio-section.text.dokumentasi-antarmuka-dan-hasil-kerja-sistem-yan": "Dokumentasi antarmuka dan hasil kerja sistem yang telah kami kembangkan\r",
    "home.portfolio-section.text.group-relative-bg-slate-900-rounded-3xl-p-3-5-h-": "group relative bg-slate-900 rounded-3xl p-3.5 h-[300px] sm:h-[350px] shadow-lg hover:shadow-2xl hover:-translate-y-2 transition-all duration-500 overflow-hidden border border-slate-800 flex flex-col justify-between",
    "home.portfolio-section.text.relative-w-full-h-80-rounded-2xl-overflow-hidden": "relative w-full h-[80%] rounded-2xl overflow-hidden bg-white flex items-center justify-center",
    "home.portfolio-section.text.object-contain-p-2-group-hover-scale-110-transit": "object-contain p-2 group-hover:scale-110 transition-transform duration-700",
    "home.portfolio-section.text.px-2-py-1-flex-items-center-justify-between-text": "px-2 py-1 flex items-center justify-between text-white",
    "home.portfolio-section.text.text-10px-font-bold-tracking-widest-text-sky-400": "text-[10px] font-bold tracking-widest text-sky-400 uppercase",
    "home.portfolio-section.text.text-sm-font-extrabold": "text-sm font-extrabold",
    "home.portfolio-section.text.w-8-h-8-rounded-full-bg-white-10-flex-items-cent": "w-8 h-8 rounded-full bg-white/10 flex items-center justify-center group-hover:bg-blue-600 transition-colors",
    "home.portfolio-section.text.w-4-h-4-text-white-group-hover-translate-x-0-5-g": "w-4 h-4 text-white group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform",
    "home.portfolio-section.text.alert": "alert",
    "home.portfolio-section.text.text-center-text-xs-text-rose-600-py-6": "text-center text-xs text-rose-600 py-6",
    "home.portfolio-section.text.text-center-text-xs-text-slate-400-py-6": "text-center text-xs text-slate-400 py-6",
    "home.portfolio-section.text.portofolio-belum-tersedia": "Portofolio belum tersedia.",
    "home.cta-section.text.scalable-reliable-solutions": "Scalable & Reliable Solutions",
    "home.cta-section.text.ready-to-scale-your": "Ready to Scale Your ",
    "home.cta-section.text.business-operations": "Business Operations?",
    "home.cta-section.text.mulai-transformasi-efisiensi-operasional-dan-tal": "Mulai transformasi efisiensi operasional dan talenta terbaik bisnis Anda hari ini bersama tim profesional kami.\r",
    "home.cta-section.href.contact": "/contact",
    "home.cta-section.text.hubungi-kami-sekarang": "Hubungi Kami Sekarang",
    "home.cta-section.alt.discussion": "Discussion",
    "home.feature-highlights-section.text.bg-slate-50-70-rounded-3xl-p-6-text-center-borde": "bg-slate-50/70 rounded-3xl p-6 text-center border border-slate-200/80 hover:bg-white hover:shadow-xl hover:border-blue-300 hover:-translate-y-2 transition-all duration-300 flex flex-col items-center group",
    "home.feature-highlights-section.text.w-6-h-6": "w-6 h-6",
    "home.feature-highlights-section.text.text-base-font-extrabold-text-slate-900-mb-1-5-g": "text-base font-extrabold text-slate-900 mb-1.5 group-hover:text-blue-600 transition-colors leading-snug",
    "home.feature-highlights-section.text.text-slate-500-text-xs-leading-relaxed-font-norm": "text-slate-500 text-xs leading-relaxed font-normal",
    "home.layout.text.keyframes-float-0-100-transform-translatey-0px-5": "\n        @keyframes float {\n          0%, 100% { transform: translateY(0px); }\n          50% { transform: translateY(-12px); }\n        }\n        @keyframes floatDelayed {\n          0%, 100% { transform: translateY(0px); }\n          50% { transform: translateY(12px); }\n        }\n        .animate-float {\n          animation: float 5s ease-in-out infinite;\n        }\n        .animate-float-delayed {\n          animation: floatDelayed 6s ease-in-out infinite;\n        }\n      ",
    "animated-titles.0": "IT Managed Services & Talent Management",
    "animated-titles.1": "Ops Services & Process Optimization",
    "animated-titles.2": "Customer Support & CX Management",
    "animated-titles.3": "Back Office Ops & Data Management",
    "hero-slides.0.alt": "Dashboard Preview 1",
    "hero-slides.1.alt": "Dashboard Preview 2",
    "hero-slides.2.alt": "Dashboard Preview 3",
    "hero-slides.3.alt": "Dashboard Preview 4",
    "bpo-main-service.title": "Business Process Outsourcing",
    "bpo-main-service.description": "Layanan Business Process Outsourcing (BPO) kami menyediakan solusi operasional bisnis yang komprehensif, mencakup layanan dukungan pelanggan nonstop melalui 24/7 Contact Center & Customer Service serta pendorong pertumbuhan bisnis lewat Telemarketing & Sales Support. Untuk pengelolaan keuangan dan validasi, kami menangani penagihan secara profesional melalui Collections & Payment Follow-up dan menjamin keamanan data pengguna melalui KYC & Data Verification.",
    "bpo-sub-services.0.title": "Recruitment & Headhunter",
    "bpo-sub-services.0.description": "Layanan pencarian dan penyediaan tenaga kerja profesional serta eksekutif yang disesuaikan dengan kebutuhan bisnis Anda.",
    "bpo-sub-services.0.points.0": "Staff to C-Level Search",
    "bpo-sub-services.0.points.1": "Recruitment Process Outsourcing (RPO)",
    "bpo-sub-services.0.points.2": "Talent Mapping & Market Intelligence",
    "bpo-sub-services.0.points.3": "Contract Staffing & Payroll Services",
    "bpo-sub-services.0.points.4": "Technical & Programming Talent Search",
    "bpo-sub-services.1.title": "Outsourcing Solution",
    "bpo-sub-services.1.description": "Solusi alih daya operasional untuk meningkatkan efisiensi dan pengelolaan tim kerja secara fleksibel.",
    "bpo-sub-services.1.points.0": "Employee Outsourcing",
    "bpo-sub-services.1.points.1": "Remote Workforce Management",
    "bpo-sub-services.1.points.2": "Virtual Team Setup & Monitoring",
    "bpo-sub-services.1.points.3": "Cross-Border Compliance & HR Support",
    "bpo-sub-services.2.title": "Global Relations & Business Support",
    "bpo-sub-services.2.description": "Dukungan ekspansi bisnis internasional dan konsultasi strategis lintas negara di Asia Tenggara hingga Eropa.",
    "bpo-sub-services.2.points.0": "Building international partnerships across SEA, East Asia, Europe",
    "bpo-sub-services.2.points.1": "Market entry advisory & localization support",
    "bpo-sub-services.2.points.2": "Business matching and cross-border collaboration",
    "bpo-sub-services.2.points.3": "Strategic consulting for global expansion",
    "bpo-sub-services.2.points.4": "Research & Market Insight capabilities",
    "bpo-cards.0.title": "CX | Contact Center\n(Customer Service)",
    "bpo-cards.0.desc": "Diagnosa, Map Journeys & Scripts, Operate with QC, Weekly Reporting & Improvements",
    "bpo-cards.0.alt": "CX Contact Center Avatar",
    "bpo-cards.1.title": "Sales Telesales",
    "bpo-cards.1.desc": "Segment & Script, Outreach & Logging, Weekly Coaching, Optimize Message & Target",
    "bpo-cards.1.alt": "Sales Telesales Avatar",
    "bpo-cards.2.title": "Collection",
    "bpo-cards.2.desc": "Bucket Mapping, Communication Strategy, Execution & Negotiation, Results Review",
    "bpo-cards.2.alt": "Collection Icon",
    "bpo-cards.3.title": "KYC Verification",
    "bpo-cards.3.desc": "Data Intake, Stepwise Verification, Clarification, Archiving & Reporting",
    "bpo-cards.3.alt": "KYC Icon",
    "control-items.0.title": "Short SOPs per Function",
    "control-items.0.description": "Easy to understand and repeat across teams with clear, standardized operational guidelines.",
    "control-items.1.title": "QA Scorecards & Coaching",
    "control-items.1.description": "Steady quality and performance consistency through regular feedback loops and evaluation.",
    "control-items.2.title": "Real-time Dashboards",
    "control-items.2.description": "Faster, evidence-based decisions with live data analytics and a clean audit trail.",
    "integrations.0.title": "Sobot (Omnichannel Platform)",
    "integrations.0.sub": "One place for voice / chat / tickets",
    "integrations.0.desc": "Shorter response times & zero tab-hopping",
    "integrations.1.title": "Mitel (Voice Analytics & AI IVR)",
    "integrations.1.sub": "Auto transcripts, summaries, talk/listen balance & QA dashboards",
    "integrations.1.desc": "Objective coaching & actionable insights",
    "integrations.2.title": "Selective Integrations Hub",
    "integrations.2.sub": "CRM & BI connectors for seamless data flow",
    "integrations.2.desc": "Data stays connected, never scattered",
    "scale-cards.0.step": "01",
    "scale-cards.0.title": "Employee & Team Outsourcing",
    "scale-cards.0.alt": "Employee & Team Outsourcing Icon",
    "scale-cards.0.badge": "Scale Rapidly",
    "scale-cards.1.step": "02",
    "scale-cards.1.title": "Remote Workforce Management",
    "scale-cards.1.alt": "Remote Workforce Management Icon",
    "scale-cards.1.badge": "Global Reach",
    "scale-cards.2.step": "03",
    "scale-cards.2.title": "Virtual Team Setup & Monitoring",
    "scale-cards.2.alt": "Virtual Team Setup & Monitoring Icon",
    "scale-cards.2.badge": "Real-time Control",
    "scale-cards.3.step": "04",
    "scale-cards.3.title": "Cross-Border Compliance & HR Support",
    "scale-cards.3.alt": "Cross-Border Compliance & HR Support Icon",
    "scale-cards.3.badge": "100% Compliant",
    "deliver-steps.0.step": "01",
    "deliver-steps.0.title": "Client Need Identification",
    "deliver-steps.0.desc": "Analisis mendalam terhadap kebutuhan & kualifikasi spesifik bisnis Anda.",
    "deliver-steps.0.alt": "Client Need Identification Icon",
    "deliver-steps.1.step": "02",
    "deliver-steps.1.title": "Talent / Team Selection",
    "deliver-steps.1.desc": "Proses seleksi ketat untuk mencocokkan kandidat/tim terbaik.",
    "deliver-steps.1.alt": "Talent Selection Icon",
    "deliver-steps.2.step": "03",
    "deliver-steps.2.title": "Onboarding & Equipment Setup",
    "deliver-steps.2.desc": "Penyiapan infrastruktur, perangkat, dan integrasi awal tim.",
    "deliver-steps.2.alt": "Onboarding & Setup Icon",
    "deliver-steps.3.step": "04",
    "deliver-steps.3.title": "Live Monitoring & Reporting",
    "deliver-steps.3.desc": "Pengawasan operasional harian beserta laporan kinerja real-time.",
    "deliver-steps.3.alt": "Live Monitoring Icon",
    "global-points.0.text": "Connect with potential partners, clients, or distributors across strategic Asian & European markets.",
    "global-points.1.text": "Expert guidance on regulatory frameworks, local culture, and tailored business practices.",
    "global-points.2.text": "Establish a robust local operational footprint with flexible, fully compliant solutions.",
    "global-points.3.text": "Gain priority access to a curated network of investors, suppliers, and strategic industry allies.",
    "global-steps.0.step": "01",
    "global-steps.0.title": "Discovery Call &\nBusiness Need",
    "global-steps.0.desc": "Pemetaan kebutuhan bisnis awal dan konsultasi eksklusif.",
    "global-steps.1.step": "02",
    "global-steps.1.title": "Market Research &\nLocalization Plan",
    "global-steps.1.desc": "Riset pasar mendalam dan penyesuaian strategi lokal.",
    "global-steps.2.step": "03",
    "global-steps.2.title": "Business Matching &\nLocal Contacts",
    "global-steps.2.desc": "Menghubungkan dengan mitra dan jaringan lokal tepercaya.",
    "global-steps.3.step": "04",
    "global-steps.3.title": "Virtual Rep Office &\nOps Setup",
    "global-steps.3.desc": "Pendirian kantor virtual dan infrastruktur operasional.",
    "global-steps.4.step": "05",
    "global-steps.4.title": "Ongoing Advisory &\nMonitoring",
    "global-steps.4.desc": "Dukungan konsultasi berkala dan pengawasan kualitatif.",
    "feature-highlights.0.title": "Layanan Ujung-ke-Ujung",
    "feature-highlights.0.description": "Layanan menyeluruh dari analisis, perancangan, pengembangan, hingga pemeliharaan oleh tim profesional.",
    "feature-highlights.1.title": "Mitra Resmi & Tepercaya",
    "feature-highlights.1.description": "Mitra resmi Google dan Sobot.io, bukti pengakuan standar global atas solusi andal kami.",
    "feature-highlights.2.title": "ROI yang Terukur",
    "feature-highlights.2.description": "Berfokus pada efisiensi biaya, akselerasi proses, serta kepuasan pelanggan secara konkrit.",
    "feature-highlights.3.title": "Keamanan & Kepatuhan",
    "feature-highlights.3.description": "Prioritas tertinggi pada kepatuhan regulasi dan standar keamanan data global.",
  },
  about: {
    "default-missions.0": "Provide flexible, scalable, and results-driven BPO services tailored to client needs.",
    "default-missions.1": "Support companies in discovering and managing top talent through professional recruitment and headhunting services.",
    "default-missions.2": "Build and strengthen global networks across countries to unlock cross-border business opportunities.",
    "default-missions.3": "Integrate technology, data, and human resource expertise to ensure consistent performance and value creation.",
    "default-missions.4": "Maintain a client satisfaction rate above 95% through transparency, accountability, and continuous performance tracking.",
    "default-missions.5": "Develop internal talent into world-class, adaptive, and globally competitive teams.",
    "default-missions.6": "Continuously innovate work models to deliver high ROI and sustainable business efficiency for clients.",
    "about.layout.text.google-partner": "Google Partner",
    "about.layout.text.miitel": "MiiTel",
    "about.layout.text.sobot": "Sobot",
    "about.layout.text.shopee": "Shopee",
    "about.layout.text.tiktok": "TikTok",
    "about.hero-about-us.text.about-teknoloka-prima-services": "About Teknoloka Prima Services\r",
    "about.hero-about-us.text.accelerating-scale": "Accelerating Scale.",
    "about.hero-about-us.text.unlocking-global-talent": "Unlocking Global Talent.\r",
    "about.hero-about-us.text.established-in-2025-pt-teknoloka-prima-service-w": "Established in 2025, PT Teknoloka Prima Service was founded to answer the growing demand for flexible, innovative, and results-driven business solutions. We specialize in Business Process Outsourcing (BPO), Recruitment & Headhunter Services, and Global Outsourcing.\r",
    "about.hero-about-us.text.backed-by-senior-professionals-with-more-than-15": "Backed by senior professionals with more than 15 years of proven expertise in BPO operations, recruitment strategy, process management, and technology-driven outsourcing, we bring deep expertise across multiple business industries.\r",
    "about.hero-about-us.text.global-reach": "Global Reach\r",
    "about.hero-about-us.text.end-to-end-solutions": "End-to-End Solutions\r",
    "about.hero-about-us.text.high-growth-roi": "High Growth ROI\r",
    "about.hero-about-us.alt.teknoloka-prima-services-team": "Teknoloka Prima Services Team",
    "about.hero-about-us.text.our-strategic-expertise": "Our Strategic Expertise",
    "about.hero-about-us.text.empowering-businesses-across-regions": "Empowering Businesses Across Regions",
    "about.vision-mission-section.text.strategic-foundation": "Strategic Foundation\r",
    "about.vision-mission-section.text.driven-by-vision-powered-by-mission": "Driven by Vision, Powered by Mission\r",
    "about.vision-mission-section.text.our-core-purpose-and-operational-commitments-dri": "Our core purpose and operational commitments driving sustainable growth for partners worldwide.\r",
    "about.vision-mission-section.text.our-vision-statement": "Our Vision Statement",
    "about.vision-mission-section.text.building-the-future-of-strategic-partnerships-in": "\"Building the Future of Strategic Partnerships in Southeast Asia\"\r",
    "about.vision-mission-section.text.95": "95%+",
    "about.vision-mission-section.text.client-satisfaction": "Client Satisfaction",
    "about.vision-mission-section.text.sea": "SEA",
    "about.vision-mission-section.text.regional-focus": "Regional Focus",
    "about.vision-mission-section.text.our-mission-pillars": "Our Mission Pillars\r",
    "about.vision-mission-section.text.core-action-items-guiding-our-everyday-operation": "Core action items guiding our everyday operations\r",
    "about.vision-mission-section.text.strategic-goals": "Strategic Goals",
    "about.vision-mission-section.text.0": "0",
    "about.vision-mission-section.text.bg-gradient-to-br-from-white-via-slate-50-90-to-": "bg-gradient-to-br from-white via-slate-50/90 to-blue-50/60",
    "about.vision-mission-section.text.bg-gradient-to-r-from-0b2545-to-2b5ba3-text-whit": "bg-gradient-to-r from-[#0b2545] to-[#2b5ba3] text-white shadow-md shadow-blue-900/20",
    "about.vision-mission-section.text.bg-gradient-to-r-from-0b2545-via-2b5ba3-to-06b6d": "bg-gradient-to-r from-[#0b2545] via-[#2b5ba3] to-[#06b6d4]",
    "about.vision-mission-section.text.hover-border-blue-300": "hover:border-blue-300",
    "about.vision-mission-section.text.hover-shadow-blue-500-10": "hover:shadow-blue-500/10",
    "about.vision-mission-section.text.group-hover-text-2b5ba3": "group-hover:text-[#2b5ba3]",
    "about.vision-mission-section.text.bg-gradient-to-br-from-white-via-sky-50-40-to-in": "bg-gradient-to-br from-white via-sky-50/40 to-indigo-50/50",
    "about.vision-mission-section.text.bg-gradient-to-r-from-2b5ba3-to-1565c0-text-whit": "bg-gradient-to-r from-[#2b5ba3] to-[#1565c0] text-white shadow-md shadow-blue-600/20",
    "about.vision-mission-section.text.bg-gradient-to-r-from-2b5ba3-via-1565c0-to-38bdf": "bg-gradient-to-r from-[#2b5ba3] via-[#1565c0] to-[#38bdf8]",
    "about.vision-mission-section.text.hover-border-sky-300": "hover:border-sky-300",
    "about.vision-mission-section.text.hover-shadow-sky-500-10": "hover:shadow-sky-500/10",
    "about.vision-mission-section.text.group-hover-text-1565c0": "group-hover:text-[#1565c0]",
    "about.vision-mission-section.text.bg-gradient-to-br-from-white-via-amber-50-30-to-": "bg-gradient-to-br from-white via-amber-50/30 to-orange-50/40",
    "about.vision-mission-section.text.bg-gradient-to-r-from-f57c00-to-ff9800-text-whit": "bg-gradient-to-r from-[#f57c00] to-[#ff9800] text-white shadow-md shadow-orange-500/20",
    "about.vision-mission-section.text.bg-gradient-to-r-from-f57c00-via-ff9800-to-ffc10": "bg-gradient-to-r from-[#f57c00] via-[#ff9800] to-[#ffc107]",
    "about.vision-mission-section.text.hover-border-amber-300": "hover:border-amber-300",
    "about.vision-mission-section.text.hover-shadow-amber-500-10": "hover:shadow-amber-500/10",
    "about.vision-mission-section.text.group-hover-text-f57c00": "group-hover:text-[#f57c00]",
    "about.vision-mission-section.text.flex-justify-between-items-center-mb-3-pt-1": "flex justify-between items-center mb-3 pt-1",
    "about.vision-mission-section.text.text-xs-sm-text-sm-text-slate-700-leading-relaxe": "text-xs sm:text-sm text-slate-700 leading-relaxed font-semibold",
    "about.vision-mission-section.text.mt-4-pt-2-5-border-t-border-slate-200-60-flex-it": "mt-4 pt-2.5 border-t border-slate-200/60 flex items-center justify-between opacity-0 group-hover:opacity-100 transition-opacity duration-300",
    "about.vision-mission-section.text.text-10px-font-black-uppercase-tracking-wider-te": "text-[10px] font-black uppercase tracking-wider text-slate-400",
    "about.vision-mission-section.text.w-3-5-h-3-5-text-2b5ba3": "w-3.5 h-3.5 text-[#2b5ba3]",
    "about.vision-mission-section.text.strategic-goal": "Strategic Goal\r",
    "about.our-core-values.text.our-dna": "Our DNA\r",
    "about.our-core-values.text.core-values": "CORE VALUES\r",
    "about.our-core-values.text.the-core-principles-that-guide-our-work-culture-": "The core principles that guide our work, culture, and strategic decisions\r",
    "about.our-core-values.text.teknoloka-values": "Teknoloka Values\r",
    "about.our-core-values.text.click-icon-to-view-detail": "Click Icon to View Detail\r",
    "about.our-core-values.text.absolute-z-20-transition-transform-duration-75-e": "absolute z-20 transition-transform duration-75 ease-linear",
    "about.our-core-values.text.button": "button",
    "about.our-core-values.text.w-6-h-6": "w-6 h-6",
    "about.our-core-values.text.w-6-h-6-2": "w-6 h-6",
    "about.our-core-values.text.bg-white-p-6-rounded-3xl-border-border-slate-200": "bg-white p-6 rounded-3xl border border-slate-200/80 shadow-xl space-y-3 transition-all duration-300 relative overflow-hidden",
    "about.our-core-values.text.absolute-top-0-right-0-w-32-h-2b5ba3-10-bg-blue-": "absolute top-0 right-0 w-32 h-[#2b5ba3]/10 bg-blue-50 rounded-bl-full -z-10",
    "about.our-core-values.text.flex-items-center-gap-4": "flex items-center gap-4",
    "about.our-core-values.text.w-6-h-6-3": "w-6 h-6",
    "about.our-core-values.text.text-10px-font-black-text-2b5ba3-uppercase-track": "text-[10px] font-black text-[#2b5ba3] uppercase tracking-widest block",
    "about.our-core-values.text.text-2xl-font-black-text-0f172a-tracking-tight": "text-2xl font-black text-[#0f172a] tracking-tight",
    "about.our-core-values.text.text-slate-600-text-sm-md-text-base-leading-rela": "text-slate-600 text-sm md:text-base leading-relaxed border-l-4 border-[#2b5ba3] pl-4 py-1 font-normal",
    "about.our-core-values.text.w-6-h-6-4": "w-6 h-6",
    "about.our-core-values.text.selected-value": "Selected Value",
    "about.our-core-values.text.w-4-h-4": "w-4 h-4",
    "about.our-core-values.text.text-xs-font-black-text-slate-800-tracking-wide-": "text-xs font-black text-slate-800 tracking-wide uppercase",
    "about.our-core-values.text.w-4-h-4-2": "w-4 h-4",
    "about.our-facilities.text.infrastructure-capabilities": "Infrastructure & Capabilities\r",
    "about.our-facilities.text.our-facilities": "OUR FACILITIES\r",
    "about.our-facilities.text.bg-gradient-to-br-from-white-via-slate-50-90-to-": "bg-gradient-to-br from-white via-slate-50/90 to-blue-50/60",
    "about.our-facilities.text.bg-gradient-to-br-from-0b2545-to-2b5ba3": "bg-gradient-to-br from-[#0b2545] to-[#2b5ba3]",
    "about.our-facilities.text.bg-gradient-to-r-from-0b2545-via-2b5ba3-to-06b6d": "bg-gradient-to-r from-[#0b2545] via-[#2b5ba3] to-[#06b6d4]",
    "about.our-facilities.text.hover-border-blue-400": "hover:border-blue-400",
    "about.our-facilities.text.hover-shadow-blue-500-15": "hover:shadow-blue-500/15",
    "about.our-facilities.text.bg-gradient-to-br-from-white-via-amber-50-30-to-": "bg-gradient-to-br from-white via-amber-50/30 to-orange-50/50",
    "about.our-facilities.text.bg-gradient-to-br-from-f57c00-to-ff9800": "bg-gradient-to-br from-[#f57c00] to-[#ff9800]",
    "about.our-facilities.text.bg-gradient-to-r-from-f57c00-via-ff9800-to-ffc10": "bg-gradient-to-r from-[#f57c00] via-[#ff9800] to-[#ffc107]",
    "about.our-facilities.text.hover-border-amber-400": "hover:border-amber-400",
    "about.our-facilities.text.hover-shadow-amber-500-15": "hover:shadow-amber-500/15",
    "about.our-facilities.text.bg-gradient-to-br-from-white-via-indigo-50-30-to": "bg-gradient-to-br from-white via-indigo-50/30 to-sky-50/50",
    "about.our-facilities.text.bg-gradient-to-br-from-1565c0-to-0288d1": "bg-gradient-to-br from-[#1565c0] to-[#0288d1]",
    "about.our-facilities.text.bg-gradient-to-r-from-1565c0-via-0288d1-to-00acc": "bg-gradient-to-r from-[#1565c0] via-[#0288d1] to-[#00acc1]",
    "about.our-facilities.text.hover-border-sky-400": "hover:border-sky-400",
    "about.our-facilities.text.hover-shadow-sky-500-15": "hover:shadow-sky-500/15",
    "about.our-facilities.text.flex-items-start-gap-3-5": "flex items-start gap-3.5",
    "about.our-facilities.text.w-5-h-5-text-white": "w-5 h-5 text-white",
    "about.our-facilities.text.space-y-0-5": "space-y-0.5",
    "about.our-facilities.text.text-10px-font-extrabold-text-slate-400-uppercas": "text-[10px] font-extrabold text-slate-400 uppercase tracking-widest block",
    "about.our-facilities.text.0": "0",
    "about.our-facilities.text.text-xs-md-text-sm-text-slate-800-leading-relaxe": "text-xs md:text-sm text-slate-800 leading-relaxed font-semibold group-hover:text-slate-950 transition-colors",
    "about.our-facilities.text.mt-4-pt-2-5-border-t-border-slate-200-60-flex-it": "mt-4 pt-2.5 border-t border-slate-200/60 flex items-center justify-between opacity-80 group-hover:opacity-100 transition-opacity",
    "about.our-facilities.text.text-10px-font-extrabold-uppercase-tracking-wide": "text-[10px] font-extrabold uppercase tracking-wider bg-gradient-to-r from-[#0b2545] to-[#2b5ba3] bg-clip-text text-transparent",
    "about.our-facilities.text.w-4-h-4-text-emerald-500": "w-4 h-4 text-emerald-500",
    "about.our-facilities.text.w-5-h-5-text-white-2": "w-5 h-5 text-white",
    "about.our-facilities.text.facility": "Facility #",
    "about.our-facilities.text.0-2": "0",
    "about.our-facilities.text.teknoloka-standard": "Teknoloka Standard\r",
    "about.our-executive-team.text.leadership": "Leadership\r",
    "about.our-executive-team.text.our-executive-team": "Our Executive Team\r",
    "about.our-executive-team.alt.eufrasia-primita-ardani": "Eufrasia Primita Ardani",
    "about.our-executive-team.text.executive-leadership": "Executive Leadership\r",
    "about.our-executive-team.text.eufrasia-primita-ardani": "Eufrasia Primita Ardani\r",
    "about.our-executive-team.text.co-founder-business-strategist-at-teknoloka": "Co-Founder & Business Strategist at Teknoloka\r",
    "about.our-executive-team.text.over-a-decade-of-experience-in-market-research-m": "Over a decade of experience in market research, marketing strategy, and business development.\r",
    "about.our-executive-team.text.started-career-in-2009-at-nielsen-building-a-str": "Started career in 2009 at Nielsen, building a strong reputation as a leader who deeply understands consumer behavior.\r",
    "about.our-executive-team.text.drives-business-strategy-and-strategic-partner-r": "Drives business strategy and strategic partner relations at Teknoloka to deliver relevant, impactful, and ethical technology solutions.\r",
    "about.our-executive-team.text.building-a-business-is-not-just-about-hitting-ta": "?Building a business is not just about hitting targets, but fostering trust that creates long-term impact.?\r",
    "about.our-executive-team.href.https-www-linkedin-com-in-eufrasia-ardani-529041": "https://www.linkedin.com/in/eufrasia-ardani-52904168",
    "about.our-executive-team.text.linkedin-profile": "LinkedIn Profile",
    "about.our-executive-team.href.contact": "/contact",
    "about.our-executive-team.text.contact-us": "Contact Us",
    "about.our-trusted-partners.text.our-trusted-partners": "Our Trusted Partners\r",
    "about.our-trusted-partners.text.who-we-work-with-us-for-the-technology-ecosystem": "Who we work with us for the technology ecosystem, Stronger together product + enablement + local execution\r",
    "values.integrity.title": "INTEGRITY",
    "values.integrity.desc": "Upholding honesty, transparency, and accountability in every process.",
    "values.innovation.title": "INNOVATION",
    "values.innovation.desc": "Constantly seeking new and creative ways to solve client challenges.",
    "values.collaboration.title": "COLLABORATION",
    "values.collaboration.desc": "Working closely with clients as strategic partners, not just a vendor.",
    "values.agility.title": "AGILITY",
    "values.agility.desc": "Responding swiftly to market changes and client needs.",
    "values.excellence.title": "EXCELLENCE",
    "values.excellence.desc": "Delivering service quality that exceeds expectations.",
    "facilities.1.text": "Information Security management is ISO 27001 certified",
    "facilities.2.text": "Server room with 24 hour dedicated IT Support",
    "facilities.3.text": "Complete amenities etc, pantry, dining room, smoking area, praying room, relax room, transit room for agents who is ill",
    "facilities.4.text": "24 hours operation and security: CCTV and Access Door",
    "facilities.5.text": "IT Development, dedicated team ready to help client integrate the system with Teknoloka Okta Perkasa (TOP).",
    "facilities.6.text": "Workstation equipped with Laptop/PC and Headset, Wallboard",
    "facilities.7.text": "Online training facilities: meeting room, coaching rooms, and training room with a total of 100 seats. All occupied with WIFI",
    "facilities.8.text": "Data center bandwidth 2 layers, main 100 Mbps with backup link fiberoptic and secondary 100 Mbps with backup link wireless( all dedicated)",
    "facilities.9.text": "Two layers UPS and genset electrical backup, UPS capacity 10 KVA for datacenter and 600va for each workstation",
  },
  services: {
    "recruitment-features.0.title": "Expertise",
    "recruitment-features.0.badge": "Core Advantage",
    "recruitment-features.0.description": "Our recruitment consultants bring an average of 15 years of experience, applying time-tested methodologies and international best practices to search, shortlist, and deliver highly qualified candidates.",
    "recruitment-features.1.title": "Quality of Candidates",
    "recruitment-features.1.description": "With access to a comprehensive talent database and strong industry networks, we ensure that every candidate we present is not only technically competent but also fits your organization's culture and values.",
    "recruitment-features.2.title": "Time Saving",
    "recruitment-features.2.description": "By leveraging our broad talent pool, market intelligence, and established networks, we enable a faster and more efficient hiring process, reducing the time-to-hire significantly.",
    "recruitment-features.3.title": "Culture Driven",
    "recruitment-features.3.description": "We go beyond qualifications, understanding what matters to your organization to ensure the talent we recommend will thrive in your culture, community, and long-term goals.",
    "recruitment-features.4.title": "Broad Industry & Role Coverage",
    "recruitment-features.4.description": "Our recruitment services cover multiple industries and roles at every level, from entry-level staff and mid-management to senior leadership and C-Level executives, making us a trusted partner in building strong teams.",
    "rpo-key-points.0.bold": "End-to-end ownership:",
    "rpo-key-points.0.text": "from job brief to onboarding (incl. 90-day success).",
    "rpo-key-points.1.bold": "Embedded partnership:",
    "rpo-key-points.1.text": "seamless extension of your internal HR team with a shared hiring playbook.",
    "rpo-key-points.2.bold": "SLA-driven delivery:",
    "rpo-key-points.2.text": "3-7 business-day shortlist and clear funnel targets (Submittal → Interview → Offer → Accept).",
    "rpo-key-points.3.bold": "Staff-to-C-Level coverage,",
    "rpo-key-points.3.text": "including technical/programming roles.",
    "rpo-key-points.4.bold": "Data-driven, bias-aware hiring:",
    "rpo-key-points.4.text": "structured scorecards, interviewer calibration, and funnel KPIs.",
    "rpo-key-points.5.bold": "Secure & compliant:",
    "rpo-key-points.5.text": "UU PDP/PDPA/GDPR, ISO 27001.",
    "talent-mapping-cards.0.title": "Benchmark & Salary Data",
    "talent-mapping-cards.0.desc": "Akurasi data gaji dan kompensasi pasar terkini untuk efisiensi budget SDM.",
    "talent-mapping-cards.1.title": "Insights Across Regions",
    "talent-mapping-cards.1.desc": "Analisis mendalam ketersediaan talenta berbasis wilayah dan geografis.",
    "talent-mapping-cards.2.title": "Passive Talent Mapping",
    "talent-mapping-cards.2.desc": "Pemetaan kandidat potensial pasif terbaik yang siap direkrut sesuai kebutuhan.",
    "talent-mapping-cards.3.title": "Reports & Dashboards",
    "talent-mapping-cards.3.desc": "Visualisasi laporan dan dashboard intuitif untuk pengambilan keputusan strategis.",
    "bpo-cards.0.title": "CX | Contact Center",
    "bpo-cards.0.subtitle": "(Customer Service)",
    "bpo-cards.0.0.outcomes.label": "Faster Responses",
    "bpo-cards.0.1.outcomes.label": "Lower cost per contact",
    "bpo-cards.0.2.outcomes.label": "Stable CSAT",
    "bpo-cards.0.0.flowSteps.label": "Diagnosa",
    "bpo-cards.0.1.flowSteps.label": "Map Journeys & Scripts",
    "bpo-cards.0.2.flowSteps.label": "Operate with QC",
    "bpo-cards.0.3.flowSteps.label": "Weekly Reporting & Improvements",
    "bpo-cards.0.whatWeDo": "Trained CS teams, contextual scripts, QA & coaching cadence, clear dashboards",
    "bpo-cards.1.title": "Sales Telesales",
    "bpo-cards.1.0.outcomes.label": "More meaningful conversations",
    "bpo-cards.1.1.outcomes.label": "More meetings / closings",
    "bpo-cards.1.0.flowSteps.label": "Segment & Script",
    "bpo-cards.1.1.flowSteps.label": "Outreach & Logging",
    "bpo-cards.1.2.flowSteps.label": "Weekly Coaching",
    "bpo-cards.1.3.flowSteps.label": "Optimize Message & Target",
    "bpo-cards.1.whatWeDo": "Human-sounding scripts, coaching driven by conversation insights, daily snapshots (connect, booked, next actions).",
    "bpo-cards.2.title": "Collection",
    "bpo-cards.2.0.outcomes.label": "Better FPD & recovery",
    "bpo-cards.2.1.outcomes.label": "With a respectful approach",
    "bpo-cards.2.0.flowSteps.label": "Bucket Mapping",
    "bpo-cards.2.1.flowSteps.label": "Communication Strategy",
    "bpo-cards.2.2.flowSteps.label": "Execution & Negotiation",
    "bpo-cards.2.3.flowSteps.label": "Results Review",
    "bpo-cards.2.whatWeDo": "Bucket-specific handling, clear escalation, compliant documentation.",
    "bpo-cards.3.title": "KYC (Verification)",
    "bpo-cards.3.0.outcomes.label": "Accurate and fast verification",
    "bpo-cards.3.1.outcomes.label": "Audit-ready",
    "bpo-cards.3.0.flowSteps.label": "Data Intake",
    "bpo-cards.3.1.flowSteps.label": "Stepwise Verification",
    "bpo-cards.3.2.flowSteps.label": "Clarification",
    "bpo-cards.3.3.flowSteps.label": "Archiving & Reporting",
    "bpo-cards.3.whatWeDo": "Consistent checks, quality controls, traceable records.",
    "services.hero-section.text.enterprise-solutions": "Enterprise Solutions",
    "services.hero-section.text.what-we-can-do-for-you": "What We Can Do For You\r",
    "services.hero-section.text.we-are-your-strategic-partner-not-just-building-": "We are your strategic partner — not just building systems, but ensuring technology becomes the foundation of sustainable growth and operational excellence.\r",
    "services.hero-section.alt.our-services-team": "Our Services Team",
    "services.layout.text.max-w-6xl-mx-auto-px-6-py-6-w-full": "max-w-6xl mx-auto px-6 py-6 w-full",
    "services.layout.text.bg-white-rounded-3xl-border-border-blue-100-shad": "bg-white rounded-3xl border border-blue-100 shadow-sm p-6 md:p-8",
    "services.layout.text.text-center-max-w-2xl-mx-auto-mb-6": "text-center max-w-2xl mx-auto mb-6",
    "services.layout.text.text-10px-font-bold-tracking-widest-text-blue-70": "text-[10px] font-bold tracking-widest text-blue-700 uppercase bg-blue-50 px-3 py-1 rounded-full border border-blue-100 inline-block mb-2",
    "services.layout.text.text-xl-md-text-2xl-font-black-text-slate-900": "text-xl md:text-2xl font-black text-slate-900",
    "services.layout.text.text-xs-text-slate-500-mt-1": "text-xs text-slate-500 mt-1",
    "services.layout.text.grid-grid-cols-1-md-grid-cols-2-gap-4": "grid grid-cols-1 md:grid-cols-2 gap-4",
    "services.layout.text.rounded-2xl-border-border-slate-200-bg-slate-50-": "rounded-2xl border border-slate-200 bg-slate-50/70 p-5",
    "services.layout.text.text-10px-font-bold-uppercase-tracking-wider-tex": "text-[10px] font-bold uppercase tracking-wider text-blue-700",
    "services.layout.text.mt-1-text-base-font-extrabold-text-slate-900": "mt-1 text-base font-extrabold text-slate-900",
    "services.layout.text.mt-2-text-sm-leading-relaxed-text-slate-600": "mt-2 text-sm leading-relaxed text-slate-600",
    "services.subtle-gradient-glow-behind-image.text.prima-services": "Prima Services\r",
    "services.subtle-gradient-glow-behind-image.text.layanan-kami": "Layanan Kami\r",
    "services.subtle-gradient-glow-behind-image.text.katalog-layanan-terbaru-dari-tim-prima-services": "Katalog layanan terbaru dari tim Prima Services.\r",
    "services.catalog.error": "Katalog layanan belum dapat dimuat. Silakan coba lagi nanti.",
    "services.subtle-gradient-glow-behind-image.text.rounded-2xl-border-border-slate-200-bg-slate-50-": "rounded-2xl border border-slate-200 bg-slate-50/70 p-5",
    "services.subtle-gradient-glow-behind-image.text.text-10px-font-bold-uppercase-tracking-wider-tex": "text-[10px] font-bold uppercase tracking-wider text-blue-700",
    "services.subtle-gradient-glow-behind-image.text.mt-1-text-base-font-extrabold-text-slate-900": "mt-1 text-base font-extrabold text-slate-900",
    "services.subtle-gradient-glow-behind-image.text.mt-2-text-sm-leading-relaxed-text-slate-600": "mt-2 text-sm leading-relaxed text-slate-600",
    "services.subtle-gradient-glow-behind-image.text.mt-2-text-sm-leading-relaxed-text-slate-600-2": "mt-2 text-sm leading-relaxed text-slate-600",
    "services.layout.text.alert": "alert",
    "services.layout.text.mx-auto-max-w-6xl-px-6-py-4-text-center-text-sm-": "mx-auto max-w-6xl px-6 py-4 text-center text-sm text-rose-600",
    "services.prima-service-recruitment-section.text.talent-acquisition-solutions": "Talent Acquisition Solutions\r",
    "services.prima-service-recruitment-section.text.prima-service-recruitment": "Prima Service Recruitment\r",
    "services.prima-service-recruitment-section.text.at": "At ",
    "services.prima-service-recruitment-section.text.prima-service": "Prima Service",
    "services.prima-service-recruitment-section.text.our-recruitment-division-is-dedicated-to-helping": ", our recruitment division is dedicated to helping businesses find and retain top-tier talent efficiently, spanning staff-level roles up to C-Level executives.\r",
    "services.prima-service-recruitment-section.text.copy": "“",
    "services.prima-service-recruitment-section.text.from-staff-to-c-level-we-deliver-the-right-talen": "From Staff to C-Level: We Deliver the Right Talent.\r",
    "services.prima-service-recruitment-section.text.proven-15-years-track-record": "Proven 15+ Years Track Record",
    "services.prima-service-recruitment-section.text.font-bold-text-sm-text-slate-900-mb-2-group-hove": "font-bold text-sm text-slate-900 mb-2 group-hover:text-blue-600 transition-colors",
    "services.prima-service-recruitment-section.text.text-xs-text-slate-500-leading-relaxed-font-norm": "text-xs text-slate-500 leading-relaxed font-normal",
    "services.recruitment-process-outsourcing-rpo-section.text.recruitment-process-outsourcing-rpo": "RECRUITMENT PROCESS OUTSOURCING (RPO)\r",
    "services.recruitment-process-outsourcing-rpo-section.text.full-cycle-hiring-with-recruitment-process-outso": "Full-Cycle Hiring with Recruitment Process Outsourcing (RPO)\r",
    "services.recruitment-process-outsourcing-rpo-section.text.rpo": "RPO",
    "services.recruitment-process-outsourcing-rpo-section.text.full-cycle-hiring": "Full-Cycle Hiring",
    "services.recruitment-process-outsourcing-rpo-section.text.01": "01",
    "services.recruitment-process-outsourcing-rpo-section.text.job-request": "Job Request",
    "services.recruitment-process-outsourcing-rpo-section.text.02": "02",
    "services.recruitment-process-outsourcing-rpo-section.text.sourcing": "Sourcing",
    "services.recruitment-process-outsourcing-rpo-section.text.03": "03",
    "services.recruitment-process-outsourcing-rpo-section.text.assessment": "Assessment",
    "services.recruitment-process-outsourcing-rpo-section.text.04": "04",
    "services.recruitment-process-outsourcing-rpo-section.text.interview": "Interview",
    "services.recruitment-process-outsourcing-rpo-section.text.05": "05",
    "services.recruitment-process-outsourcing-rpo-section.text.offer": "Offer",
    "services.recruitment-process-outsourcing-rpo-section.text.06": "06",
    "services.recruitment-process-outsourcing-rpo-section.text.onboard": "Onboard",
    "services.recruitment-process-outsourcing-rpo-section.text.key-program-pillars": "Key Program Pillars\r",
    "services.recruitment-process-outsourcing-rpo-section.text.flex-items-start-gap-2-5-text-xs-text-slate-600-": "flex items-start gap-2.5 text-xs text-slate-600 leading-normal",
    "services.recruitment-process-outsourcing-rpo-section.text.mt-1-w-1-5-h-1-5-rounded-full-bg-blue-600-shrink": "mt-1 w-1.5 h-1.5 rounded-full bg-blue-600 shrink-0",
    "services.recruitment-process-outsourcing-rpo-section.text.flex-1": "flex-1",
    "services.recruitment-process-outsourcing-rpo-section.text.text-slate-900-font-bold-mr-1": "text-slate-900 font-bold mr-1",
    "services.recruitment-process-outsourcing-rpo-section.text.text-slate-600-font-normal": "text-slate-600 font-normal",
    "services.talent-mapping-market-intelligence-section.text.market-intelligence": "MARKET INTELLIGENCE\r",
    "services.talent-mapping-market-intelligence-section.text.talent-mapping": "TALENT MAPPING &",
    "services.talent-mapping-market-intelligence-section.text.market-intelligence-2": "MARKET INTELLIGENCE\r",
    "services.talent-mapping-market-intelligence-section.text.understanding-the-talent-market-is-essential-to-": "Understanding the talent market is essential to staying competitive. Prima Service provides actionable insights on workforce availability, salary benchmarks, and future hiring trends.\r",
    "services.talent-mapping-market-intelligence-section.text.flex-justify-between-items-start-mb-4-pt-1": "flex justify-between items-start mb-4 pt-1",
    "services.talent-mapping-market-intelligence-section.text.text-xs-font-extrabold-text-slate-900-tracking-t": "text-xs font-extrabold text-slate-900 tracking-tight mb-1.5 group-hover:text-[#0b2545] transition-colors",
    "services.talent-mapping-market-intelligence-section.text.text-11px-text-slate-600-leading-relaxed-font-no": "text-[11px] text-slate-600 leading-relaxed font-normal",
    "services.talent-mapping-market-intelligence-section.text.mt-5-pt-3-border-t-border-slate-200-60-flex-item": "mt-5 pt-3 border-t border-slate-200/60 flex items-center justify-between",
    "services.talent-mapping-market-intelligence-section.text.copy": "#",
    "services.talent-mapping-market-intelligence-section.text.w-3-h-3-transition-transform-duration-200-group-": "w-3 h-3 transition-transform duration-200 group-hover/link:translate-x-1",
    "services.talent-mapping-market-intelligence-section.text.none": "none",
    "services.talent-mapping-market-intelligence-section.text.currentcolor": "currentColor",
    "services.talent-mapping-market-intelligence-section.text.0-0-24-24": "0 0 24 24",
    "services.talent-mapping-market-intelligence-section.text.round": "round",
    "services.talent-mapping-market-intelligence-section.text.round-2": "round",
    "services.talent-mapping-market-intelligence-section.text.2": "2",
    "services.talent-mapping-market-intelligence-section.text.m9-5l7-7-7-7": "M9 5l7 7-7 7",
    "services.talent-mapping-market-intelligence-section.text.w-3-5-h-3-5-text-slate-300-group-hover-text-blue": "w-3.5 h-3.5 text-slate-300 group-hover:text-blue-500 transition-colors",
    "services.talent-mapping-market-intelligence-section.text.currentcolor-2": "currentColor",
    "services.talent-mapping-market-intelligence-section.text.0-0-24-24-2": "0 0 24 24",
    "services.talent-mapping-market-intelligence-section.text.m12-2l14-5-9-5l22-12l14-5-14-5l12-22l9-5-14-5l12": "M12 2L14.5 9.5L22 12L14.5 14.5L12 22L9.5 14.5L12 22L9.5 14.5L2 12L9.5 9.5L12 2Z",
    "services.talent-mapping-market-intelligence-section.text.0": "0",
    "services.talent-mapping-market-intelligence-section.href.copy": "#",
    "services.talent-mapping-market-intelligence-section.text.explore-details": "Explore Details",
    "services.bpo-detail-section.text.solutions-deep-dive": "Solutions Deep-Dive\r",
    "services.bpo-detail-section.text.business-process-outsourcing-bpo": "Business Process Outsourcing (BPO)\r",
    "services.bpo-detail-section.text.your-comprehensive-target-driven-technology-oper": "Your comprehensive target-driven technology & operational services\r",
    "services.bpo-detail-section.text.bg-white-text-slate-900-rounded-2xl-p-5-md-p-6-b": "bg-white text-slate-900 rounded-2xl p-5 md:p-6 border border-slate-200/80 shadow-xs hover:shadow-md transition-all duration-300 group relative overflow-hidden text-left",
    "services.bpo-detail-section.text.grid-grid-cols-1-md-grid-cols-12-gap-6-items-cen": "grid grid-cols-1 md:grid-cols-12 gap-6 items-center relative z-10",
    "services.bpo-detail-section.text.md-col-span-4-flex-items-center-border-b-md-bord": "md:col-span-4 flex items-center border-b md:border-b-0 md:border-r border-slate-100 pr-0 md:pr-6 pb-4 md:pb-0 h-full",
    "services.bpo-detail-section.text.flex-flex-col-items-center-text-center-w-full": "flex flex-col items-center text-center w-full",
    "services.bpo-detail-section.text.relative-w-20-h-20-rounded-xl-bg-slate-50-flex-i": "relative w-20 h-20 rounded-xl bg-slate-50 flex items-center justify-center mb-2.5 overflow-hidden p-2 transition-transform duration-300 group-hover:scale-105 border border-slate-100 shadow-inner",
    "services.bpo-detail-section.text.object-contain": "object-contain",
    "services.bpo-detail-section.text.font-extrabold-text-sm-text-slate-900-leading-ti": "font-extrabold text-sm text-slate-900 leading-tight",
    "services.bpo-detail-section.text.text-11px-font-semibold-text-slate-400-mt-0-5": "text-[11px] font-semibold text-slate-400 mt-0.5",
    "services.bpo-detail-section.text.md-col-span-8-space-y-4": "md:col-span-8 space-y-4",
    "services.bpo-detail-section.text.text-10px-font-bold-text-slate-400-uppercase-tra": "text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-2.5",
    "services.bpo-detail-section.text.relative-grid-grid-cols-4-gap-2-text-center": "relative grid grid-cols-4 gap-2 text-center",
    "services.bpo-detail-section.text.absolute-top-4-left-6-right-6-h-0-5-bg-slate-100": "absolute top-4 left-6 right-6 h-0.5 bg-slate-100 -z-0 hidden md:block",
    "services.bpo-detail-section.text.flex-flex-col-items-center-group-step-cursor-poi": "flex flex-col items-center group/step cursor-pointer relative z-10",
    "services.bpo-detail-section.text.relative-w-8-h-8-mb-1-5": "relative w-8 h-8 mb-1.5",
    "services.bpo-detail-section.text.absolute-top-1-left-1-w-4-h-4-bg-white-border-bo": "absolute -top-1 -left-1 w-4 h-4 bg-white border border-slate-200 rounded-full text-[9px] font-bold text-slate-800 flex items-center justify-center z-20 shadow-xs",
    "services.bpo-detail-section.text.text-10px-font-semibold-text-slate-600-leading-t": "text-[10px] font-semibold text-slate-600 leading-tight px-1 transition-colors group-hover/step:text-slate-900",
    "services.bpo-detail-section.text.grid-grid-cols-1-sm-grid-cols-12-gap-3-items-str": "grid grid-cols-1 sm:grid-cols-12 gap-3 items-stretch pt-3 border-t border-slate-100",
    "services.bpo-detail-section.text.sm-col-span-7-flex-flex-col-justify-between": "sm:col-span-7 flex flex-col justify-between",
    "services.bpo-detail-section.text.text-10px-font-bold-text-slate-400-uppercase-tra-2": "text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1.5",
    "services.bpo-detail-section.text.flex-flex-wrap-gap-1-5-items-center": "flex flex-wrap gap-1.5 items-center",
    "services.bpo-detail-section.text.flex-items-center-gap-1-5-bg-slate-50-px-2-5-py-": "flex items-center gap-1.5 bg-slate-50 px-2.5 py-1 rounded-full border border-slate-200/70",
    "services.bpo-detail-section.text.text-xs": "text-xs",
    "services.bpo-detail-section.text.text-10px-font-semibold-text-slate-700-leading-t": "text-[10px] font-semibold text-slate-700 leading-tight",
    "services.bpo-detail-section.text.sm-col-span-5-bg-slate-50-80-border-border-slate": "sm:col-span-5 bg-slate-50/80 border border-slate-200/70 p-3 rounded-xl text-[10px] flex flex-col justify-center",
    "services.bpo-detail-section.text.font-bold-text-slate-900-mb-0-5": "font-bold text-slate-900 mb-0.5",
    "services.bpo-detail-section.text.text-slate-500-leading-relaxed-font-normal": "text-slate-500 leading-relaxed font-normal",
    "services.bpo-detail-section.text.text-11px-font-semibold-text-slate-400-mt-0-5-2": "text-[11px] font-semibold text-slate-400 mt-0.5",
    "services.bpo-detail-section.text.execution-flow": "Execution Flow\r",
    "services.bpo-detail-section.text.flex-flex-col-items-center-group-step-cursor-poi-2": "flex flex-col items-center group/step cursor-pointer relative z-10",
    "services.bpo-detail-section.text.relative-w-8-h-8-mb-1-5-2": "relative w-8 h-8 mb-1.5",
    "services.bpo-detail-section.text.absolute-top-1-left-1-w-4-h-4-bg-white-border-bo-2": "absolute -top-1 -left-1 w-4 h-4 bg-white border border-slate-200 rounded-full text-[9px] font-bold text-slate-800 flex items-center justify-center z-20 shadow-xs",
    "services.bpo-detail-section.text.text-10px-font-semibold-text-slate-600-leading-t-2": "text-[10px] font-semibold text-slate-600 leading-tight px-1 transition-colors group-hover/step:text-slate-900",
    "services.bpo-detail-section.text.target-outcomes": "Target Outcomes\r",
    "services.bpo-detail-section.text.flex-items-center-gap-1-5-bg-slate-50-px-2-5-py--2": "flex items-center gap-1.5 bg-slate-50 px-2.5 py-1 rounded-full border border-slate-200/70",
    "services.bpo-detail-section.text.text-xs-2": "text-xs",
    "services.bpo-detail-section.text.text-10px-font-semibold-text-slate-700-leading-t-2": "text-[10px] font-semibold text-slate-700 leading-tight",
    "services.bpo-detail-section.text.what-we-do": "What we do:\r",
    "catalog.error": "Katalog layanan belum dapat dimuat. Silakan coba lagi nanti.",
  },
};
