import type { PageContentMap } from "@/lib/page-content-types";

export const SHARED_PAGE_CONTENT_DEFAULTS: PageContentMap = {
  shared: {
    "navigation.logo.alt": "Prima Services Logo",
    "navigation.logo.href": "/",
    "navigation.home.label": "Home",
    "navigation.home.href": "/",
    "navigation.about.label": "About Us",
    "navigation.about.href": "/about",
    "navigation.services.label": "Services",
    "navigation.services.href": "/services",
    "navigation.contact.label": "Contact",
    "navigation.contact.href": "/contact",
    "navigation.cta.label": "Free Consultant Now",
    "navigation.cta.href": "/contact",
    "footer.brand.name-primary": "Teknoloka",
    "footer.brand.name-secondary": "Prima Services",
    "footer.brand.initial": "T",
    "footer.tagline": "Teknoloka Prima Services helps businesses achieve digital transformation through trusted software development, IT services, UI/UX design, cybersecurity, cloud solutions, and ISO consulting.",
    "footer.availability": "Available for New Projects",
    "footer.company.title": "Company",
    "footer.company.home.label": "Home",
    "footer.company.home.href": "/",
    "footer.company.about.label": "About Us",
    "footer.company.about.href": "/about",
    "footer.company.services.label": "Services",
    "footer.company.services.href": "/services",
    "footer.company.contact.label": "Contact",
    "footer.company.contact.href": "/contact",
    "footer.solutions.title": "Solutions",
    "footer.solutions.sobot.label": "Sobot.io - AI Contact Center",
    "footer.solutions.sobot.href": "/solutions/sobot",
    "footer.solutions.workspace.label": "Google Workspace - Business",
    "footer.solutions.workspace.href": "/solutions/workspace",
    "footer.solutions.cloud.label": "Google Cloud - Computing",
    "footer.solutions.cloud.href": "/solutions/cloud",
    "footer.solutions.it.label": "IT Managed Services",
    "footer.solutions.it.href": "/solutions/it",
    "footer.solutions.iso.label": "ISO Assistance & Compliance",
    "footer.solutions.iso.href": "/solutions/iso",
    "footer.social.title": "Follow Us",
    "footer.social.facebook.label": "Facebook",
    "footer.social.instagram.label": "Instagram",
    "footer.social.linkedin.label": "LinkedIn",
    "footer.social.linkedin.href": "https://www.linkedin.com/in/eufrasia-ardani-52904168/",
    "footer.social.youtube.label": "YouTube",
    "footer.contact.title": "Address & Contact",
    "footer.contact.jakarta-office.label": "Jakarta Office",
    "footer.contact.jakarta-office.address": "Permata Hijau, Bellezza BSA, Jl. Permata Hijau No.106 lt. 1, Grogol Utara, Jakarta Selatan, 12210",
    "footer.contact.yogyakarta-office.label": "Yogyakarta Office",
    "footer.contact.yogyakarta-office.address": "Jl. Magelang No.188, Karangwaru, Kec. Tegalrejo, Kota Yogyakarta, 55242",
    "footer.contact.phone.label": "+62 821-5009-1305",
    "footer.contact.phone.href": "tel:+6282150091305",
    "footer.contact.email.label": "business@teknoloka.co.id",
    "footer.contact.email.href": "mailto:business@teknoloka.co.id",
    "footer.copyright": "PT Teknoloka Prima Services. All rights reserved.",
    "footer.privacy.label": "Privacy Policy",
    "footer.privacy.href": "/privacy-policy",
    "footer.terms.label": "Terms & Conditions",
    "footer.terms.href": "/terms-and-conditions",
    "footer.back-to-top.title": "Back to top",
  },
};
